var __IntegralASDiagnosticCall = (function(code, err, config) {
	try {
		var alreadySent = false;
		return function(code, err, config) {
			try {
				if (!alreadySent) {
					alreadySent = true;
					if (config) {
						// cannot stringify DOM node due to parent-child relationship
						config.thisScriptNode = '';
					}
	
					var img = new Image();
					img.src = '//fw.adsafeprotected.com/jsdiagnostic' +
						'?code:' + code +
						'&err:' + encodeURIComponent(err.message) +
						'&config:' + encodeURIComponent(JSON.stringify(config));
				}
			} catch(err) {}
		};
	} catch(err) {
		return function(){};
	}
})();

try {
	var __IntegralASConfig = {
		jsDoSplit : "false",
		cocaPuffsPath : "",
		debug : "false",
		killPhrases : "",
		useAdTalk : "true",
		jsDiag:'true',
		version:'0',
		mtCell: 10,
		mtSample: 5,
		cookieDomain:'sc.iasds01.com/dtc',
		trackMouse : "true",
		exchList:{'e1':'nqzryq','e2':'tbbtyrnqf.t.qbhoyrpyvpx','e3':'ehovpbacebwrpg','e4':'chozngvp','e5':'bcrak','e6':'nqoevgr.pbz','e7':'tynz.pbz','e8':'lvryqznantre.pbz','e9':'yvwvg','e10':'nqakf','p11':'ghea.pbz','p12':'zngugnt','p13':'vaivgrzrqvn','p14':'qngnkh','n15':'zrqvn6qrterrf','n16':'dhnagfreir','n17':'esvuho.arg','a18':'napubeserr','a19':'eff2frnepu','a20':'mgfgngvp.pbz','n21':'ovq.npr.nqiregvfvat','e22':'wnfba','v23':'fcbgkpqa','v24':'ogeyy','v25':'yvirenvy','v26':'nqncgi','v27':'nqnc.gi','n29':'qbzqrk.pbz','n30':'ernyih.arg','d31':'cvengronl','d32':'cebklonl','d33':'onlcebkl','d34':'cvengrcebkl','d35':'cebklcvengr','d36':'onlcvengr'},
		protocol:'http',
		jsref : "http://solarviews.com/eng/privacy.htm",
		asid : "c124904e-2105-11e5-9a5b-00259036a18a",
		allowViewability : "true",
		jsFeatures : "mousetrack:0,cocoapuffs,viewabilityready,consecutive,cachebust:0,forcecocoa:0,rattie:0,exch,recordalternate:100,usedtdomain,nextcocoa:0,bapiDiag,cookie,postDts:0,unreliabilityDetection,videotwoseconds,getPl,decodePl,resolution,usetpl,usesca:1,tpiLookupURL,hundredpct,jloadDiag:0,cdnTest:1,blur,sendclogs,zeroPing,idMap,offscreen,everySecond:1,sdkdetection",
		adTalkDtCall : "true",
		adsafeDomain : "adsafeprotected.com:80",
		minimizeCalls : "false",
		adWidth : "728",
		adHeight : "90",
		forceAppend : "false",
		mode : "jss",
		_onAPIResult : __IntegralASConfig && __IntegralASConfig.onAPIResult,
		_onInViewMRC15 : __IntegralASConfig && __IntegralASConfig.onInViewMRC15,
		_onMeasurable : __IntegralASConfig && __IntegralASConfig.onMeasurable,
		_onSuspicious : __IntegralASConfig && __IntegralASConfig.onSuspicious,
		_onInViewMRC : __IntegralASConfig && __IntegralASConfig.onInViewMRC,
		_onInViewMRC5 : __IntegralASConfig && __IntegralASConfig.onInViewMRC5,
		requrl : "",
		reqquery : "",
		dtBaseURL: "http://dt.adsafeprotected.com/dt",
		adsafeSrc : "http://pixel.adsafeprotected.com/rfw/st/33364/3423285/skeleton.js",
		adsafeSep : "?",
		tpiLookupURL:"",
		getTpl: "false",
		use100v: false,
		useBapiCallback: "",
		useViewabilityNotification: "",
		scriptUrl : "http://pixel.adsafeprotected.com/rjss/st/33364/3423285/skeleton.js",
		accountForSadImps:'',
		sendCookie:'true',
		fwMonitoring:'true',
		cdnTestUrl: "//cdn.adsafeprotected.com/cdn-test.js",
		colloTestUrl: "//pixel.adsafeprotected.com/jload?campId=cdnTest&anId=100",
		doNothing: false,
		cdnTestEnabled: false,
		mn: "app08",
		cdnTestEnabled: false,
		mobOrTab: false,
		mobFwUrl : "http://mobile.adsafeprotected.com/internal/monitoring/app/initial/33364/3423285/",
		videoId : ''
	};

	if (__IntegralASConfig.jsFeatures.indexOf('asidJsDiagnostic') !== -1) {
		var fakeErr = { message: __IntegralASConfig.asid };
		__IntegralASDiagnosticCall('asid', fakeErr);
	}

	__IntegralASConfig.birthdate = new Date().getTime();
	__IntegralASConfig.thisScriptNode = (function() {
		var tempScript,
			embedded = window != top,
			scripts = document.getElementsByTagName('script'),
			result = scripts[scripts.length - 1],
			scriptIndex = scripts.length,
			useDocWrite = 'jss,jsi,jspix'.indexOf(__IntegralASConfig.mode) !== -1,
			scriptUrl = __IntegralASConfig.scriptUrl;

		try {
			while (--scriptIndex >= 0) {
				tempScript = scripts[scriptIndex];
				if (tempScript.src && tempScript.src.indexOf(scriptUrl) === 0 && tempScript.getAttribute('data-ias-script-tag') === null) {
					result = tempScript;
					tempScript.setAttribute('data-ias-script-tag', 'found');
					break;
				}
			}
			if (scriptIndex === 0 && useDocWrite && !embedded) {
				document.write('<span id="s' + __IntegralASConfig.asid + '"/>');
				result = document.getElementById('s' + __IntegralASConfig.asid).parentNode;
			}
		} catch(e) { }
	
		return result;
	}());

} catch(err) {
	__IntegralASConfig = {};
	__IntegralASDiagnosticCall('bootstrapper', err);
}

__IntegralASConfig.initialize=function(l){var u,Oa=function(){u=new S;var a=-1!==l.mode.indexOf("jsvid"),d=e.isDef(window.JSON)&&e.isDef(window.postMessage),d="true"===l.useAdTalk&&d,b,c,f,g,p,k=W(),m=X(),q=ga(u),n=ha(),r=new ia(u),D=ja(k),B=ka(),y=la(),z=ma(),A=na(),A=oa(n,A),x=pa(n),E=qa(n),C=ra(n),N=sa(),J=ta(C),t=ua(C),v=a?va(y):{},w=a?wa(l.videoId,k,u,y,v):{},a=xa(N,n,t,u,J,z,w,k),N=ya(a,n,D),F=za(a,n,k,E,r,C,y,m,w,v),v=Aa(A,F,q),H=Ba(n,k,u,q),q=Ca(A,F,n,E,r),m=Da(A,F),H=Ea(H,A,k,z.isMobileApp()),
G=Fa(C,F,n,k,t,u,E,J,r,v,z,D,N,y,w),D=Ga(A,n,k,E,H,r,C,G),y=Ha(u),z=Ia(u);F.setViewabilityMod(G);k.on("sdkdetection")&&l.mobOrTab&&Ja(C,s);d&&(b=Ka(n));var C="0"!==C.getFlashVersion(),I,E=!G.useFlash();if(!function(){var a=!1,b,c;try{e.isDef(l)&&e.isDef(l.killPhrases)&&""!==l.killPhrases&&(b=l.adsafeSrc?l.adsafeSrc:l.requrl+l.reqquery,c=l.killPhrases.split(","),e(c).each(function(d,m){m=decodeURIComponent(c[d]).replace(/^\s+|\s+$/g,"");-1!==b.search(m)&&(a=!0)})),l.doNothing&&(a=!0)}catch(d){n.add(h.ERROR_CODES.KILL_IT)}return a}()){if(d)try{b.createAdProxy(l),
b.findFrames(),b.listen(),b.sendMessages(),r.addItem(b.getFrameStore(),"fm"),k.on("idMap")&&(c=b.getIdMap())&&r.addItem(c,"idMap")}catch(T){n.add(h.ERROR_CODES.ADTALK_GENERAL)}var L;try{"true"!==l.minimizeCalls&&G.init();k.on("mousetrack")&&(p=La(a,r),p.init());L=B.detectTopURL();k.on("exch")&&(f=Ma(n,r),f.parse(L));if(k.on("getPl")&&navigator&&navigator.plugins){g=Na(navigator.plugins);var P=g.hash();r.addItem({output:P.join(".")},"pl",{type:h.DT_CODES.ADTALK});if(k.on("decodePl")&&P.length){var Q=
g.decode(P);r.addItem({output:Q.join(".")},"pd",{type:h.DT_CODES.ADTALK})}}var M=x.getProps();e(M).each(function(a,b){r.addItem({output:b},a,{type:"UFO"})})}catch(K){n.add(h.ERROR_CODES.IMPRESSION_LEADUP)}F.sendCookie();D.send(L);k.on("cdnTest")&&l.cdnTestEnabled&&z.init();"true"===l.useViewabilityNotification&&l._onMeasurable&&(E||C)&&A.notify(l._onMeasurable);"http"===l.protocol&&"true"===l.getTpl&&k.on("usetpl")&&q.init();l.tpiLookupURL&&m.init(l.tpiLookupURL);"true"===l.adTalkDtCall&&"true"!==
l.minimizeCalls&&(I=(new Date).getTime(),s.execAtEndOfThread(function(){s.execAtEndOfThread(function(){var a={output:(new Date).getTime()-I};r.addItem(a,"sinceFw",{type:h.DT_CODES.ADTALK});e.isDef(G.readyFired())&&r.addItem({output:G.readyFired()},"readyFired",{type:h.DT_CODES.ADTALK});F.send(h.DT_CODES.ADTALK)})}));k.on("usesca")&&y.load()}},e=function(a){var d=function(c){return a instanceof Object&&(c||!b())},b=function(){return a instanceof Array},c=function(b,c){if(a.length===+a.length)for(var d=
0,g=a.length;d<g;++d)b(d,a[d]);else for(d in a)(a.hasOwnProperty(d)||c)&&b(d,a[d])},f=function(a,b){var d=[];c(function(c,g){var f=a(c,g);if(void 0!==f||b)d[d.length]=f});return d},g=function(a,b){b=b||",";var d=[];c(function(b,c){var g=a(b,c);e.isDef(g)&&d.push(g)});return d.join(b)},p=function(a,b,c){for(var d in b)e.isDef(b[d])&&(c||b.hasOwnProperty(d))&&(a[d]=b[d]);return a},k=function(a){var b={};c(function(c,g){var f=a(c,g);d(f)&&p(b,f)});return b};return{each:c,isObj:d,isArray:b,invert:function(){return k(function(a,
b){var c={};c[b]=a;return c})},mapToObj:k,map:f,keys:function(){var a=[];c(function(b){a.push(b)});return a},toParams:function(a){return g(function(a,b){return"string"===typeof a&&-1!==a.indexOf("NULL")?b:a+":"+b},a)},stringify:g,toION:function(c,g){var n,r="[",k="]";g=g||0;c=c||{};if(4<++g)return"object";if(!d(!0))return a;b()?n=f(function(a,b){return e(b).toION(c,g)}):(r="{",k="}",n=f(function(a,b){return(c[a]||a)+":"+e(b).toION(c,g)}));return r+n.join(",")+k},compareTo:function(a){var b=!1;c(function(c,
d){a[c]!==d&&(b||(b={}),b[c]=d)});return b},mixin:function(b,c){return p(a,b,c)},find:function(a){var b;c(function(c,d){a(c,d)&&(b=d)});return b},asStrings:function(){var a={};c(function(b,c){a[b]=""+c});return a},selectProperties:function(b){var c={};e(b).each(function(b,d){e.isDef(a[d])&&(c[d]=a[d])});return c},toArray:function(){return f(function(a,b){return b})}}};e.toBase=function(a,d){var b,c=0>a,f="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),g=[];a=c?-a:a;do b=
a%d,g.push(f[b]),a=(a-b)/d;while(0<a);g=g.reverse().join("");return c?"-"+g:g};e.isDef=function(a){return"undefined"!==typeof a};e.isUndef=function(a){return!e.isDef(a)};e.noop=function(){};e.identity=function(a){return a};e.isFunction=function(a){return"function"===typeof a};e.useIfDef=function(a){return e.isDef(a)?a:!1};e.stringifyTriState=function(a){return!0===a?1:!1===a?0:"na"};e.flatJSONParse=function(a){var d,b,c,f=/"(\w+)":(\d+|(?:"([^"]*)"))/g,g={};for(c=f.exec(a);c;)d=c[1],b=c[3],c=c[2],
g[d]=b||+c,c=f.exec(a);return g};var Pa=function(a,d,b,c,f,g,p){g=g||c.parentNode||c.parent;var k=function(){var b=t.embedded?a.calcDims():d.calcDims(c,g);f===h.DETECTION_METHODS.AD_PLACEHOLDER&&b.treatAsPlaceholder();return b},m=function(){var a=!l.mobOrTab&&(t.friendly||e.isDef(window.mozInnerScreenX))&&p.on("offscreen"),c=k(),d=new H(v.calcWinDims()),a=new H(a?v.calcMonDims():{});return b.calcPercentInView(c,d,a)},q=function(){return b.calcInitialViewState(m())},n=function(){return c===window?
!1:k().isHidden()};(function(){var a=c===window?document.body:c;w.addEvent(a,"click",function(){u.trigger("adComponentClicked")});w.addEvent(a,"mouseover",function(){u.trigger("adComponentMousedOver")})})();return{getAdNode:function(){return c},isNode:function(a){return c===a},isHidden:n,isObstructed:function(){return!1},getDims:k,getPercentInView:m,getLocationState:q,getOnPageViewability:function(){return n()?h.OUT_OF_VIEW:q()},getDetectionMethod:function(){return f},getContainerDims:function(){return H(g)},
refresh:function(){var a,b=c.parentNode;if(b){for(;c!==window&&b&&b!==document&&!a;)a=b===g,b=b.parentNode;a||(g=c.parentNode)}}}},Qa=function(a,d,b,c){var f=[],g=function(){return f[0]&&f[0].getDetectionMethod()===h.DETECTION_METHODS.AD_PLACEHOLDER},p=function(m,k,e){m=Pa(a,d,b,m,k,e,c);g()&&f.shift();f.push(m)},k=function(){var a=0,b=0;e(f).each(function(c,d){var g;g=d.getDims();g.hasValidDims()&&(g=g.area(),a+=g,b+=d.getPercentInView()/100*g)});return s.round(b/a*100)},m=function(){return b.calcInitialViewState(k())},
q=function(a){var b=-1;e(f).each(function(c,d){d.isNode(a)&&(b=c)});return b},n=function(a){return function(){return f[0]&&f[0][a]()}};u.on("adComponentAdded",function(a){e(a).each(function(a,b){-1===q(b)&&p(b,h.DETECTION_METHODS.MUTATION)})});u.on("adComponentRemoved",function(a){e(a).each(function(a,b){var c=q(b);-1<c&&f.splice(c,1)})});return{getOriginatingNode:n("getAdNode"),getDims:n("getDims"),isObstructed:n("isObstructed"),getDetectionMethod:n("getDetectionMethod"),getContainerDims:n("getContainerDims"),
getViewState:m,getPercentInView:k,isHidden:n("isHidden"),isUsingPlaceholder:g,hasAd:function(){return!!f.length},refresh:function(){e(f).each(function(a,b){b.refresh()})},addAdComponent:p,getOutOfViewReasons:function(){var a=[],b=f[0],c=h.OUT_OF_VIEW_REASONS,d=m();d!==h.OUT_OF_VIEW&&d!==h.PARTIAL_VIEW_MINUS||a.push(c.GEOM);b.isHidden()&&a.push(c.HIDDEN);b.isObstructed()&&a.push(c.OBSTRUCTION);return a},getComponentCount:function(){return f.length}}},Ra=function(a){var d=!1;if(!e.isUndef(window.MutationObserver)){var b=
new MutationObserver(function(a){s.execAtEndOfThread(function(){d&&e(a).each(function(a,b){b.addedNodes.length&&u.trigger("adComponentAdded",b.addedNodes);b.removedNodes.length&&u.trigger("adComponentRemoved",b.removedNodes)})})}),c=function(){d=!0;setTimeout(function(){d=!1},40)};u.on("adComponentClicked",c);u.on("adComponentMousedOver",c);try{b.observe(document.body,{attributes:!0,childList:!0,characterData:!0})}catch(f){a.add(h.ERROR_CODES.AC_WATCHER)}}},X=function(){var a=[],d={},b={percentInView:"piv",
sl:"vs",reason:"r",adDimensions:"ac",width:"w",height:"h"};u.on("newScreenEvent",function(c){c=e(c).selectProperties(e(b).keys());c=e(c).asStrings();var f=e(c).compareTo(d);f&&(f.t=t.getTagTime(),a.push(f));e(d).mixin(c)});return{toString:function(){return e(a).toION(b)}}},Sa=function(a,d,b,c,f,g,p){var k;(function(){var g=b.getRounded(),e=g.width-5,n=g.height-5,r=0.5*g.width+1,g=0.5*g.height+1;k=[new a(d,e,n,f,p,c),new a(d,e,5,f,p,c),new a(d,5,n,f,p,c),new a(d,5,5,f,p,c),new a(d,r,g,f,p,c)]})();
return{getNumInView:function(){var a=[],b=0;e(k).each(function(b,c){var d=c.isInView()?1:0;a.push(d)});g.addItem({output:a.join(".")},"pvs");e(a).each(function(a,c){b+=c});return b},getPctInView:function(a){return 5===a?100:3<=a?51:0},isReady:function(){var a=!0;e(k).each(function(b,c){c.isNotReadyToReport()&&(a=!1)});return a}}},Ta=function(a,d,b,c,f,g,p,k){var m=new a(T,document.body,d,c,f,p,k),q,n,r=0;b=b||e.noop;q=setInterval(function(){m.isReady()&&!n?(n=!0,b(),clearInterval(q)):(5===++r||n)&&
clearInterval(q)},50);return{checkViewable:function(){var a=m.isReady(),c=m.getNumInView(),c=m.getPctInView(c),d=g.calcInitialViewState(c,!0);a&&!n&&(n=!0,b());return{str:a?d:h.NA,pct:a?c:-1}}}},ba=function(a,d,b,c,f,g,p){var k,m,q=d.getRounded(),n=[],r=!1,D=0,B=function(){var a;if(!r)for(r=!0,a=0;a<n.length;a++)if(n[a].isNotReadyToReport()){r=!1;break}return r},y=function(){var a=0,b=0;e(n).each(function(c,d){b+=d.weight;d.isInView()&&(a+=d.weight)});return s.round(a/b*100)};(function(){var b=Ua(q,
1).get();e(b).each(function(b,d){var e=new a(document.body,d.x,d.y,c,f,g,p);e.weight=d.weight;n.push(e)})})();b=b||e.noop;k=setInterval(function(){B()&&!m?(m=!0,b(),clearInterval(k)):(5===++D||m)&&clearInterval(k)},50);return{checkViewable:function(){var a=B(),c;a&&(c=50<=y()?h.IN_VIEW:h.OUT_OF_VIEW);a&&!m&&(m=!0,b());return{str:a?c:h.NA,pct:a?y():-1}}}},S=function(){var a={},d=function(b,c){a[b]=a[b]||new O;a[b].push(c)};return{on:function(a,c){c?d(a,c):e(a).each(d)},trigger:function(){var b,c=e(arguments).toArray();
(b=a[c.shift()])&&b.run.apply({},c)}}},T=function(a,d,b,c,f,g,p){var k=c.on("nextcocoa"),m,q,n,r,D,B,y=function(a,b){return'<param name="'+a+'" value="'+b+'"/>'},z=function(){var a;a=new K;var b=l.cocaPuffsPath;a.sub("static");a.master(a.master().split(":")[0]);b&&(a.master(b),a.sub(""));var b=a+(k?"/detector4.pix":"/detector3.pix"),c=y("allowscriptaccess","always"),d=y("movie",b)+y("play","true")+y("loop","true");g.browserIs("i")?(a=document.createElement("div"),a.innerHTML="<object "+('id="blag'+
l.birthdate+'" ')+'classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" '+(h.IAS_DETECTOR+'="true" ')+('type="'+h.FLASH_MIME+'" ')+('data="'+b+'" ')+">"+d+c+"</object>",m=a.firstChild):(m=document.createElement("object"),m.data=b,m.type=h.FLASH_MIME,m.innerHTML=c,m[h.IAS_DETECTOR]="true");m.style.position="absolute";m.style.width="1px";m.style.opacity="0";m.style.height="0px";return m},A=function(a){a.style.height=n?"1px":"2px";n=!n;s.execAtEndOfThread(function(){if(E())try{q=a.isInView()}catch(b){x()}})},
x=function(){B=!1;u.trigger("error",h.ERROR_CODES.COCOA_GONE)},E=function(){var a=k?"getId":"isInView";(a=B||m&&e.isFunction(m[a]))&&!r&&(B=!0,k&&(r=m.getId()));return a};k&&w.addEvent(window,"message",function(a){a=e.flatJSONParse(a.data);"IASCOCOA"===a.type&&a.id===r&&(D=1===+a.isInView)});(function(a,b,c){var d=z(),g=d.style;g.left=b+"px";g.top=c+"px";a.appendChild(d);g.height="1px";f.onHiddenChange(function(a){a?g.height="0px":A(d)})})(a,d,b);return{isInView:function(){var a;if(E()){try{a=k?D:
m.isInView()}catch(b){x()}g.browserIs("w")&&a!==q&&A(m)}return E()&&a},isNotReadyToReport:function(){return!E()},createdFlash:m}},U=function(a){return{doEligibleJobs:function(d){var b=a[0],c=b&&b.time;c&&d>=c&&(b.task(),a.shift())},getNextJob:function(){return a[0]}}},ia=function(a){var d=0,b={},c=function(a,b,c){if(e.isUndef(a.output))throw Error("item with id "+b+' must have "output" method');this.item=a;this.id=b||++d;this.props=c||{};this.output=function(){return e.isFunction(a.output)?a.output():
a.output}},f=function(a,d,f){a=new c(a,d,f||{});b[a.id]=a};a.on("addOutputItem",function(a,b,c){f(a,b,c)});return{addItem:f,iterate:function(a){var c,d,f=[];for(c in b)b.hasOwnProperty(c)&&(d=a(c,b[c]))&&f.push(d);return f},getItem:function(a){return b[a]}}},Ua=function(a,d){var b,c,f,g=a.width,e=a.height,k=[],m=g/(d+1),q=e/(d+1),n=1;if(0===g||0===e)k.push({x:1,y:1,weight:1});else for(f=q;f<e;f+=q,n++)c=m*n,c>g/2&&(c=g-c),b={x:s.floor(c),y:s.floor(f),weight:1},c={x:s.floor(g-c),y:s.floor(f),weight:1},
b.x===c.x?(b.weight=2,b.x+=1,b.y+=1,k.push(b)):(k.push(b),k.push(c));return{get:function(){return k}}},O=function(){var a=[];return{push:function(d){a[a.length]=d},run:function(){var d=arguments;e(a).each(function(a,c){c.apply({},d)})}}},ya=function(a,d,b){return{collect:function(){var c=a.find(),d=c.getOutOfViewReasons(),g=b.isHidden(),p=H(v.calcWinDims()),k=c.getDims();if(!p.hasValidDims()||!k.hasValidDims())return{viewState:h.NA,posViewState:h.NA,embedded:t.embedded,winDimensions:p,adDimensions:k};
!0===g&&d.push(h.OUT_OF_VIEW_REASONS.FOCUS);return{winDimensions:p,adDimensions:k,containerDimensions:c.getContainerDims(),method:c.getDetectionMethod(),viewState:d.length?h.OUT_OF_VIEW:c.getViewState(),percentInView:c.getPercentInView(),reason:d.join("."),obstructed:e.stringifyTriState(c.isObstructed()),isHidden:e.stringifyTriState(c.isHidden()),tabHidden:e.stringifyTriState(g),posViewState:c.getViewState(),adCompCount:c.getComponentCount()}}}},Va=function(a){a=a||e.identity;var d=[],b=s.now(),c=
function(){var a=s.now();d.length&&(d[d.length-1].duration+=a-b,b=a)};return{clear:function(){c();d=[]},fastForward:c,get:function(){return d},hasAlwaysBeen:function(a){return 1===d.length&&d[0].state===a},addState:function(b){var g=d[d.length-1];b=a(b);c();0!==d.length&&b===g.state||d.push({state:b,duration:0})}}},Wa=function(a){var d=a||1,b=0,c=0,f=0,g=0;return{start:function(){0===b%d&&(f=s.now())},stop:function(){0===b%d&&(g+=s.now()-f,c++);b++},getTime:function(){return g},getCount:function(){return c}}},
ca=function(a){var d=0,b=t.getTagTime(),c=0,f,g;return{getTotalTime:function(){return c},stop:function(){d=0;b=t.getTagTime()},mark:function(){f=t.getTagTime()-b;d+=f;d>a&&(g=d-f<a,c+=g?d:f);b=t.getTagTime()}}},K=function(a){var d=/((http|https):\/\/(([^\/\.]*)\.([^\/]*)))(?:\/(.[^?]*))*/.exec(a||l.adsafeSrc||l.requrl),b=d[2],c=d[4],f=d[5],g=a?d[6]:"",p,k=function(a){e.isDef(a)&&(c=a);return c},m=function(a){e.isDef(a)&&(f=a);return f},q=function(){var a="";e(p).each(function(b,c){a+="&"+b+"=";a=
e(c).isObj()?a+("{"+e(c).toParams()+"}"):a+c});return"?"+a.substr(1)};return{fullDom:d[1],sub:k,master:m,setParam:function(a,b){p=p||{};p[a]=p[a]||{};e(b).isObj()?e(p[a]).mixin(b):p[a]=b},path:function(a){g=a},_getQsParams:function(){return p},toString:function(){var a=k()?k()+".":"",c=g?"/"+g:"",d=p?q():"";return b+"://"+a+m()+c+d}}},Xa=function(a,d){var b=!1,c=!1,f,g=function(){b||(b=!0,f=d.createViewabilityTracker("mpt",function(a){return a.isFullyInView()}))},p=function(a){if(!e.isUndef(a.eventData)){var b=
-1;e.isDef(a.eventData.volume)?b=a.eventData.volume:e.isDef(a.eventData.adVolume)&&(b=a.eventData.adVolume);return b}},k=function(a){a=p(a);b||0!==a?b&&(c||0===a)&&(a={isFullyInView:function(){return!1}},f.addState(a)):c=!0};return{init:function(){var b=function(a){k(a)};a.on({adStarted:g,adVideoStart:g,adVideoStarted:g,volumeChanged:b,adVolumeChange:b,adVideoMidpoint:function(){f&&f.hasAlwaysBeen(!0)&&a.trigger("sendDt",h.DT_CODES.QUARTILE_FULLY_INVIEW)}})}}},xa=function(a,d,b,c,f,g,e,k){var m=-1!==
l.mode.indexOf("jsvid"),q=l.thisScriptNode.parentNode,n=Qa(f,a,b,k);Ra(d);return{find:function(){var a,b=h.DETECTION_METHODS,c=function(c){var d=v.findChildWithLargestContent(q);1<v.getNodeArea(d)&&!d[h.IAS_DETECTOR]?n.addAdComponent(d,c||b.AD_HUNT,q):n.hasAd()||(a=v.getPlaceholderSpan(),q.insertBefore(a,l.thisScriptNode.nextSibling),n.addAdComponent(a,c||b.AD_PLACEHOLDER))};if(n.isUsingPlaceholder()||!n.hasAd())g.isMobileApp()?c(g.getDetectionMethod()):m?n.addAdComponent(e.findAdNode(),b.VIDEO):
t.embedded?n.addAdComponent(window,b.IFRAME):c();return n},getDetectionMethod:function(){},isAdDetected:function(){return!0!==n.isUsingPlaceholder()},getOriginatingElement:function(){return n.getOriginatingNode()},getParent:function(){return q}}},Ka=function(a){var d=[],b=function(a){var b;a=a||l;a.reqquery?b=a.reqquery.split(/(?:anId=|anid=|ANID=)([^&]*)/)[1]:(b=a.adsafeSrc.split("/"),b=b[5]+"-"+b[6]);a={adId:b,adSafeId:a.asid};d.push(a);return a},c=function(){var a=[],b={},d={noMe:!0};return{addFrame:function(c){a.push(c);
b[c.pageId]=c;c.isMe&&(d=c)},list:a,lookup:b,me:function(){return d},output:function(){var b;b=e(a).stringify(function(a,b){var c="";if(b.isLeaf||b.isMe||e.isDef(b.selfDescription))return c+=b.getStringifiedPosition(),c+=b.isMe?"*":"",c+=b.adProxies.length?"."+b.adProxies[0].adId:""},"|");return e.toBase(d.unifiedId,62)+"+"+b},getIdMap:function(){var b,d;d=c.me().getStringifiedPosition();b=e(a).stringify(function(a,b){var c;if(b.isMe)return d+"*";if(b.srcIsEmbedded&&t.embedded&&(b.isLeaf||b.isMe||
e.isDef(b.selfDescription))&&(c=b.getStringifiedPosition(),d&&c&&b.srcId&&b.transferDuration&&(0===d.indexOf(c)||0===c.indexOf(d))))return c+"."+b.srcId+"."+b.transferDuration},"|");return b=120<b.length?b.substr(0,120)+".of"+b.length:b}}},c=new c,f=function(){return{output:c.getIdMap}},f=new f,g=function(a,b,g){var f,k,m=a===window;g=g||{};f={position:b.slice(0),pageId:b.join("-"),domObj:function(){return a},isMe:m,isLeaf:!a.frames.length,adProxies:m?d:[],selfDescription:void 0,unifiedId:l.birthdate,
srcId:g.srcId,transferDuration:g.transferDuraiton,srcIsEmbedded:g.srcIsEmbedded};k=function(a){f.selfDescription=a;f.adProxies=a.adProxies};f.toString=function(){return JSON.stringify(f)};f.getStringifiedPosition=function(){return e(f.position).map(function(a,b){return e.toBase(Number(b)+1,36)}).join("")};f.addInformationFromSrc=function(a){k(a.messageContent.self);e(["srcId","transferDuration","srcIsEmbedded"]).each(function(b,c){e.isUndef(f[c])&&(f[c]=a[c])})};c.addFrame(f);return f},p;p=new function(){var a=
function(b,c){var d=c.length,f=b.frames;if(!(new g(b,c)).isLeaf){for(var e=0;e<f.length;e++)c[d]=e,a(f[e],c);c.pop()}};return{start:function(){a(top,[0])}}};var k=function(a){var b={srcId:l.asid,srcKey:l.asid.split("-")[2],srcStart:l.birthdate,replyTo:document.location,sendMessage:function(c,d){d=d||"*";a.sentTime=s.now();delete b.updateMessage;delete b.sendMessage;c.postMessage(JSON.stringify(b),d)},updateMessage:function(b){a=b(a)},messageContent:a||{},srcIsEmbedded:t.embedded};return b},m;m=new function(){var b=
[],d=function(a){var b=c.me();(new k({self:b,expectedPageId:a.pageId,unifiedId:b.unifiedId})).sendMessage(a.domObj())};return{sendMessages:function(){var a,b;for(a=0;a<c.list.length;a++)b=c.list[a],b.isMe||d(b)},listen:function(){w.addEvent(window,"message",function(f){var k,m,p,z=c.me();try{k=JSON.parse(f.data);m=k.messageContent;if(l.asid.split("-")[2]!==k.srcKey||!k.hasOwnProperty("messageContent"))return;m.unifiedId<z.unifiedId&&(z.unifiedId=m.unifiedId)}catch(A){return}b.push(k);try{if(m.expectedPageId!==
c.me().pageId)a.add(h.ERROR_CODES.ADTALK_DUBIOUS);else{k.transferDuration=s.now()-m.sentTime;p=c.lookup[m.self.pageId];if(e.isUndef(p)||e.isUndef(p.selfDescription))p=p||new g(f.source,m.self.pageId.split("-"),k),d(p);p.addInformationFromSrc(k)}}catch(x){a.add(h.ERROR_CODES.ADTALK_DUBIOUS)}})}}};return{sendMessages:m.sendMessages,listen:m.listen,findFrames:p.start,createAdProxy:function(a){return new b(a)},getFrameStore:function(){return c||""},getIdMap:function(){return f||""}}},Ca=function(a,d,
b,c,f){var g=function(a,b,c){f.addItem({output:a+"."+b+"."+c},"ctpl")},p=function(f){try{d.diagnostic("c");var m=f.length,p=0,n=0;g(m,0,0);e(f).each(function(b,d){a.send(d.replace("%%CBS%%",c.getCacheBustId()),function(){g(m,p,++n)},!0);g(m,++p,n)})}catch(r){b.add(h.ERROR_CODES.AT_SEND)}};return{init:function(){try{var c=(new K).fullDom;"/"!==c.slice(-1)&&(c+="/");c+="tpl?asId="+l.asid;a.jsonp(c,p)}catch(d){b.add(h.ERROR_CODES.AT_INIT)}}}},Ba=function(a,d,b,c){return{enabled:"true"===l.useBapiCallback,
callback:function(d){b.trigger("sendDiag");try{"true"===l.accountForSadImps&&c.measure(d),l._onAPIResult&&l._onAPIResult(d)}catch(g){a.add(h.ERROR_CODES.BAPI_CALLBACK),b.trigger("sendDiag","bapiClient")}}}},ra=function(a){var d=function(){var a=function(a){return a.replace(/\D+/g,",").match(/^,?(.+),?$/)[1].split(",").join(".")};try{try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{b.AllowScriptAccess="always"}catch(c){return"6"}}catch(d){}return a((new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))}catch(f){try{if(navigator.mimeTypes[h.FLASH_MIME].enabledPlugin)return a((navigator.plugins["Shockwave Flash 2.0"]||
navigator.plugins["Shockwave Flash"]).description)}catch(e){}}return"0"},b=function(a){return f()===a},c=function(){return document&&document.documentMode?document.documentMode:h.NA},f=function(){var a="u";try{if(e.isDef(window.opera)&&e.isDef(window.opera.buildNumber))a="o";else if(e.isDef(window.mozInnerScreenY))a="g";else if(e.isDef(window.chrome)&&e.isDef(window.chrome.csi))a="c";else if(e.isDef(window.WebKitPoint))a="w";else if(e.isDef(window.attachEvent)||e.isDef(window.msCrypto))a="i"}catch(b){}return a};
return{browserIs:b,getFlashVersion:d,getDocumentMode:c,getBrowserVendor:f,getUserAgent:function(){return e.isDef(window.navigator)&&e.isDef(window.navigator.userAgent)?window.navigator.userAgent:!1},params:function(){var a=f(),p=d(),k=5;b("i")?window.msCrypto?k=11:window.atob?k=10:document.addEventListener?k=9:window.JSON&&document.querySelector?k=8:window.XMLHttpRequest?k=7:document.compatMode&&(k=6):k=h.NA;var m=c(),q;q=["{45EA75A0-A269-11D1-B5BF-0000F8051515}","{3AF36230-A269-11D1-B5BF-0000F8051515}",
"{89820200-ECBD-11CF-8B85-00AA005B4383}"];var n=h.NA,r=document.createElement("div");try{if("-ms-ime-align"in document.documentElement.style)n="11";else{r.style.behavior="url(#default#clientcaps)";for(var l=0;l<q.length&&!(n=r.getComponentVersion(q[l],"componentid").replace(/,/g,"."));l++);}}catch(B){}q=n;n=h.NA;e.isDef(window.navigator)&&e.isDef(window.navigator.appName)&&(n=window.navigator.appName.toLowerCase()[0]);return{br:a,fv:p,bv:k,dm:m,abv:q,an:n}}}},Ia=function(a){var d=0.5<=s.random()?
"cdn":"collo",b=function(){a.trigger("sendDiag",d+"Test","cdnTest")};return{init:function(){var c,f=l[d+"TestUrl"];f&&(c=-1===f.indexOf("?")?"?":"&",f=f+c+"asid="+l.asid,a.trigger("exec",f,b))}}},oa=function(a,d){var b=function(a,b){var c,d,f=l.thisScriptNode.parentNode;b=b||a;a=1<arguments.length?a:"script";c={script:['<script type="text/javascript" src="','">\x3c/script>'],iframe:['<iframe width="100%" height="100%" frameborder="0" vspace="0" hspace="0" scrolling="no" marginheight="0" marginwidth="0" src="',
'"></iframe>'],img:['<img src="','"/>']}[a];d=c[0]+b+c[1];"true"===l.forceAppend?"script"!==a?(c=document.createElement("DIV"),c.innerHTML=d,f.appendChild(c.childNodes[0])):(c=document.createElement("SCRIPT"),c.src=b,f.appendChild(c)):document.write(d)},c=function(a,b,c){var d=!c&&w.getXHR2();d?(d.open("POST",a),d.onreadystatechange=function(){4===d.readyState&&200===d.status&&b&&b()},d.send()):(c=new Image,b&&(c.onload=b),c.src=a)},f=function(a,b){var c=document.createElement("script");c.type="text/javascript";
c.src=a;b&&(c.onload=b);e.isDef(l.thisScriptNode.parentNode)&&l.thisScriptNode.parentNode.appendChild(c)},g=function(b){e.isFunction(b)?b():"string"===typeof b?c(b,void 0,!0):a.add(h.ERROR_CODES.NOTIFY_CLIENT)};u.on({addNode:b,send:c,exec:f,notify:g});return{addNode:b,send:c,exec:f,notify:g,jsonp:function(a,b,c,g){f(d.wrap(a,b,c,g))}}},h={MAX_URL_LENGTH:2E3,FLASH_MIME:"application/x-shockwave-flash",IN_VIEW:"inView",OUT_OF_VIEW:"outOfView",PARTIAL_VIEW_PLUS:"partialViewPlus",PARTIAL_VIEW_MINUS:"partialViewMinus",
NA:"na",DT_CODES:{UNLOAD:"u",PING:"p",FULLY_INVIEW:"pf",QUARTILE_FULLY_INVIEW:"qf",ADTALK:"a",VIEWABILITY_READY:"v",VIDEO_EVENTS:"m",DIAGNOSTIC:"b",POS_INVIEW:"t",THIRD_PARTY:"i",SCA:"s"},DETECTION_METHODS:{AD_PLACEHOLDER:"s",AD_HUNT:"a",IFRAME:"i",VIDEO:"v",MOBILE:"m",MUTATION:"c"},OUT_OF_VIEW_REASONS:{GEOM:"l",OBSTRUCTION:"o",FOCUS:"f",COLLAPSED:"c",HIDDEN:"h",VIDEO:"v"},ERROR_CODES:{GET_AD_DIMENSIONS:"a",ADTALK_GENERAL:"c",GET_SCREEN_LOC_GET_DIMENSIONS:"d",EXCHANGE_PARSING:"x",PHONE_HOME:"h",KILL_IT:"k",
LOCATION_DETAILS:"l",GET_SCREEN_LOC_PIV_CALC:"p",GET_WIN_DIMENSIONS:"w",ADTALK_DUBIOUS:"D",ENVIRONMENT:"v",UID_GENERATION:"i",NOTIFY_CLIENT:"n",IMPRESSION_URLS:"I",JSINFO:"J",IMPRESSION_LEADUP:"L",GET_ELEM_STYLE:"s",PLUGIN_PARSING:"P",AT_SEND:"S",AT_INIT:"N",BAPI_CALLBACK:"b",AC_WATCHER:"W",COCOA_GONE:"C",CHECK_SCREEN_LOC:"V",NO_VIDEO_AD_NODE:"u",VIDEO_IN_IFRAME_DIMS_CALC:"F"},IAS_DETECTOR:"iasdetector"},t=function(){var a=window!=top,d=function(){var a;try{a=!!top.document}catch(c){a=!1}return a}();
return{embedded:a,friendly:d,getTagTime:function(){return s.now()-l.birthdate},getPageTime:function(){return e.isDef(window.chrome)&&e.isDef(window.chrome.csi)&&e.isFunction(window.chrome.csi)?s.round(chrome.csi().pageT):h.NA},friendlyIframe:a&&d,xDomainIframe:a&!d}}(),w={addEvent:function(a,d,b,c){e.isDef(a.addEventListener)?"mouseenter"===d?a.addEventListener("mouseover",w.mouseEnter(b),c):"mouseleave"===d?a.addEventListener("mouseout",w.mouseEnter(b),c):a.addEventListener(d,b,c):e.isDef(a.attachEvent)&&
a.attachEvent("on"+d,b)},removeEvent:function(a,d,b){e.isDef(a.removeEventListener)?("mouseenter"===d?(d="mouseover",b=w.mouseEnter):"mouseleave"===d&&(d="mouseout",b=w.mouseEnter),a.removeEventListener(d,b)):e.isDef(a.detachEvent)&&a.detachEvent("on"+d,b)},mouseEnter:function(a){var d=this;return function(b){var c=b.relatedTarget;this===c||d.isAChildOf(this,c)||a.call(this,b)}},isAChildOf:function(a,d){if(a===d)return!1;for(;d&&d!==a;)d=d.parentNode;return d===a},getStyle:function(a,d){var b="";
document.defaultView&&document.defaultView.getComputedStyle?b=document.defaultView.getComputedStyle(a,"").getPropertyValue(d):a.currentStyle&&(d=d.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),b=a.currentStyle[d]);return b},getXHR2:function(a,d){var b,c;e.isDef(window.XMLHttpRequest)?(c=new XMLHttpRequest,"withCredentials"in c&&(b=c)):e.isDef(XDomainRequest)&&(b=new XDomainRequest);return b}},za=function(a,d,b,c,f,g,p,k,m,q){var n=0,r=0,D=!1,B,y=function(a,d,f,g,e){f=f||!b.on("postDts");
if(c.impressionIsIdentifiable()&&(a===h.DT_CODES.DIAGNOSTIC||a===h.DT_CODES.ADTALK||"n"!==p.getCurrentLoc()))try{var k=l.dtBaseURL,m=new K(k),q=s.now();k||(m.path("dt"),b.on("usedtdomain")&&m.sub("dt"));A(m,a,d);e&&m.setParam(e.field,e.value);g||x(m,a,d);u.trigger("send",m,function(){r+=1;n=s.now()-q},f);a===h.DT_CODES.UNLOAD&&(D=!0)}catch(y){__IntegralASDiagnosticCall("dt-"+a,y),u.trigger("error",h.ERROR_CODES.PHONE_HOME)}},z=function(a,c){var d={bapi:"a",bapiClient:"b",jload:"c",jss:"d",jsi:"e",
cdnTest:"f",colloTest:"g"},f=l.mode,d=d[a]||d[f];b.on(c||f+"Diag")&&d&&y(h.DT_CODES.DIAGNOSTIC,-5,!0,!0,{field:"bkp",value:d})},A=function(a,b,d){if(!e.isDef(d)){var f;b===h.DT_CODES.UNLOAD?f=-1:b===h.DT_CODES.ADTALK?f=-2:b===h.DT_CODES.VIEWABILITY_READY?f=-3:b===h.DT_CODES.VIDEO_EVENTS&&q&&m?f=-4:b===h.DT_CODES.DIAGNOSTIC?f=-5:b===h.DT_CODES.THIRD_PARTY?f=-6:b===h.DT_CODES.QUARTILE_FULLY_INVIEW&&(f=-7);d=f}a.setParam("asId",l.asid);a.setParam("tv",{c:c.getCacheBustId(),pingTime:d,time:t.getTagTime(),
type:b})},x=function(a,c){p.fastForward();var e={};c===h.DT_CODES.VIDEO_EVENTS&&q&&m&&(e.ve=q.stringify(),b.on("sendclogs")&&(e.clog=k));c===h.DT_CODES.UNLOAD&&(e.ndt=r);-1!==l.mode.indexOf("jsvid")&&m&&(e.vv=m.getVersion());e.NULL1=b.output();e.NULL2=p.stringify(10);e.em=t.embedded;e.fr=t.friendly;e.uf=B.useFlash()?1:0;e.e=d.toString();e.tt=l.mode;e.dtt=n;f.iterate(function(a,b){b.props.type&&b.props.type!==c||(e[a]=b.output())});a.setParam("tv",e);a.setParam("br",g.getBrowserVendor())};u.on({sendDt:function(a,
b){y(a,b)},sendDiag:function(a,b){z(a,b)}});return{send:y,sendCookie:function(){var a;b.on("cookie")&&"true"===l.sendCookie&&l.protocol&&l.cookieDomain&&l.asid&&(a=l.protocol+"://"+l.cookieDomain+"?asid="+l.asid,u.trigger("send",a,e.noop,!0),r++)},unload:function(){D||y(h.DT_CODES.UNLOAD,-1,!0)},diagnostic:z,setViewabilityMod:function(a){B=a}}},H=function(a){var d={},b=!1,c=function(){var a={};e(d).each(function(b,c){a[b]=s.round(c)});return a};(function(){var b;a!==window.parent&&(1!==a.nodeType?
d=a:e.isDef(a.getBoundingClientRect)&&(b=v.getRect(a),e(d).mixin({x:e.useIfDef(b.x)||b.scrX,y:e.useIfDef(b.y)||b.scrY,scrX:b.scrX,scrY:b.scrY,width:b.width,height:b.height})))})();return{hasValidDims:function(){var a,b=e(d).find(function(b,c){a=!0;return isNaN(c)});return e.isDef(a)&&e.isUndef(b)},toString:function(){var a=c();return[a.scrX,a.scrY,a.width,a.height].join(".")},getRounded:c,set:function(a,b){d[a]=b},isHidden:function(){var c=1===a.nodeType?v.nodeIsHidden(a):0===a.width||0===a.height;
return b?!1:c},treatAsPlaceholder:function(){b=!0},area:function(){return s.round(d.width)*s.round(d.height)}}},sa=function(){return{calcDims:function(a,d){var b=new H(a),c=v.getClippedDimensions(a,d),f=b.getRounded();b.set("height",c.height<f.height?c.height:f.height||1);b.set("width",c.width<f.width?c.width:f.width||1);return b}}},v={nodeIsHidden:function(a){var d=this.getRect(a),b=0!==parseInt(w.getStyle(a,"width"))&&0===d.width,d=0===d.width||0===d.height;a="hidden"===w.getStyle(a,"visibility");
return b||d||a},calcWinDims:function(){var a,d,b;try{d=v.windowPosition(),b=v.windowSize(),a={scrX:s.round(d.scrX),scrY:s.round(d.scrY),width:s.round(b.width),height:s.round(b.height)}}catch(c){u.trigger("error",h.ERROR_CODES.GET_WIN_DIMENSIONS),a={}}return a},windowSize:function(){var a={},d,b;if(t.friendly)if(d=top.document,b=d.documentElement,d=d.getElementsByTagName("body")[0],e.isDef(top.innerWidth))a.width=top.innerWidth,a.height=top.innerHeight;else if(e.isDef(b.clientWidth))a.width=b.clientWidth,
a.height=b.clientHeight;else if(e.isDef(d.clientWidth))a.width=d.clientWidth,a.height=d.clientHeight;else throw a.width=a.height=0,"";else e.isDef(window.outerWidth)&&(a.width=window.outerWidth,a.height=window.outerHeight);return a},windowPosition:function(){var a=0,d=0;e.isDef(window.screenX)?(a=window.screenX,d=window.screenY):e.isDef(window.screenLeft)&&(a=window.screenLeft,d=window.screenTop);return{scrX:a,scrY:d}},getNodeArea:function(a){var d=-1;a&&(a=v.getRect(a),d=a.width*a.height);return d},
getRect:function(a){var d={},b=v.windowPosition();a=a.getBoundingClientRect();e.isUndef(a.x)&&(d.x=a.left,d.y=a.top);e.isUndef(a.width)&&(d.width=a.right-a.left,d.height=a.bottom-a.top);e(d).mixin(a,!0);d.scrX=b.scrX+d.x;d.scrY=b.scrY+d.y;return d},getIeDimObj:function(){return document.documentElement&&e.isDef(document.documentElement.clientWidth)&&document.documentElement||document.body},getPlaceholderSpan:function(){var a=document.createElement("span");e(a.style).mixin({width:"0px",height:"0px",
display:"block",overflow:"hidden",visibiility:"hidden"});a.innerHTML=".";return a},getClippedDimensions:function(a,d){var b,c,f=1E4,g=1E4;b="absolute"===w.getStyle(a,"position");if(null!==a.parentNode&&!b){do a=a.parentNode,b="OBJECT"!==a.tagName.toUpperCase(),c="inline"!==w.getStyle(a,"display"),b&&c&&(b=v.getRect(a),f=b.width<f?b.width:f,g=b.height<g?b.height:g);while(a.parentNode!==document&&a!==d)}return{width:s.round(f),height:s.round(g)}},findChildWithLargestContent:function(a){var d=function(b){for(;b.parentNode!==
a;)b=b.parentNode;return b},b=null,c=function(b){var c,d,e=null,m=-1;if(b.length)for(c=0,d=b.length;c<d;c++){var q=b[c],n=v.getNodeArea(q),r;if(r=n>m){r=void 0;if(r=q.parentNode===a)if(r=void 0,r="DIV"===q.nodeName)if(r=void 0,r=""===q.style.backgroundImage){var h=r=void 0,l=q.childNodes;for(r=0;r<l.length;r++)1===l[r].nodeType&&(h=!0);r=!h}r=!r}r&&(e=q,m=n)}return e}(function(a){var b,c,d,e,q=[],n="iframe img a object embed div".split(" ");b=0;for(c=n.length;b<c;b++){var r=a.getElementsByTagName(n[b]);
if(r.length)for(d=0,e=r.length;d<e;d++)q.push(r[d])}return q}(a));c&&(b=d(c));return b},screenSize:function(){var a={width:-1,height:-1};try{e.isDef(window.screen)&&(a={width:window.screen.width,height:window.screen.height})}catch(d){}return a},calcMonDims:function(){var a=e(v.screenSize()).mixin({scrX:0,scrY:0});e.isDef(screen.availLeft)&&(a={scrX:window.screen.availLeft,scrY:window.screen.availTop,width:window.screen.availWidth,height:window.screen.availHeight});return a}},pa=function(a){return{getProps:function(){var d=
{};try{var b=document.createElement("span");e(b.style).mixin({position:"absolute",top:"150"});d={rpx:""===b.style.top?1:0}}catch(c){a.add(h.ERROR_CODES.ENVIRONMENT)}return d}}},ha=function(){var a={},d=function(b){e.isDef(a[b])?a[b]++:a[b]=1};u.on("error",function(a){d(a)});return{list:a,add:d,toString:function(){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=c);return b},hasErrors:function(){for(var b in a)return!0;return!1}}},Ma=function(a,d){var b=function(a){var b=[];if(a&&a instanceof Array)b=
e(a).map(function(a,b){return b.val}),b.push(l.adsafeSrc,l.requrl,l.reqquery);else throw Error("Unexpected data type in ExchangeParser.getUrlList");return b};return{parse:function(c){try{var f,g=b(c),p=g&&g.length&&g.join("|"),k=l.exchList;p&&(f=e(k).map(function(a,b){return 0<=p.indexOf(R.rot(b))?a:void 0}),f.length&&d.addItem({output:f.join(".")},"ex",{type:"UFO"}))}catch(m){a.add(h.ERROR_CODES.EXCHANGE_PARSING)}}}},W=function(){var a={},d=function(b,c){var d=RegExp(b+"(?=$|,)|"+b+":(?!,|$)(.?\\d*(?=,|$))").exec(l.jsFeatures);
if(e.isUndef(a[b])||c)a[b]=!!(d&&!d[1]||d&&d[1]>100*s.random());return a[b]},b={bl:"blur",fc:"forcecocoa",rt:"rattie",cb:"cachebust",np:"nextcocoa",th:"tabHiddenDtCall",es:"everySecond"},c=function(){return e(b).mapToObj(function(b,c){var d={};d[b]=a[c]?1:0;return d})};e(b).each(function(a,b){d(b)});return{on:d,output:function(){return e(c()).toParams()}}},ua=function(a){var d=a.browserIs("g")||a.browserIs("i")||t.friendlyIframe||!t.embedded;return{calcInitialViewState:function(a,c){var e=h.NA;if(d||
c)e=75<=a?h.IN_VIEW:25>=a?h.OUT_OF_VIEW:50<=a?h.PARTIAL_VIEW_PLUS:h.PARTIAL_VIEW_MINUS;return e},calcPercentInView:function(a,c,d){var g=0,p=a;a.hasValidDims()&&!a.isHidden()&&(e([c,d]).each(function(a,b){if(b.hasValidDims()){var c=p.getRounded(),d=b.getRounded(),e=Math.max(c.scrX,d.scrX),g=Math.max(c.scrY,d.scrY),f=Math.min(c.scrX+c.width,d.scrX+d.width),c=Math.min(c.scrY+c.height,d.scrY+d.height),f=f-e,c=c-g;p=H({scrX:e,scrY:g,width:0<f?f:0,height:0<c?c:0})}}),g=s.round(p.area()/a.area()*100));
return g}}},qa=function(a){var d=!1;return{getCacheBustId:function(){var a=new Date,c=Date.parse("Jan 1 "+a.getFullYear()),a=a.getTime()-c;return e.toBase(a,62)},impressionIsIdentifiable:function(a){a&&(d=!0);return d},unq:function(){var b="";try{for(var c,d=window.Uint32Array&&window.crypto&&window.crypto.getRandomValues;30>b.length;)d?(c=new Uint32Array(1),window.crypto.getRandomValues(c),b+=c[0].toString(16)):b+=(16*s.random()|0).toString(16);b=b.slice(0,30)}catch(e){a.add(h.ERROR_CODES.UID_GENERATION)}return b}()}},
ta=function(a){var d,b=function(){var b,c,d,m,h;t.friendly?(b=f(),c=b.left,d=b.top,b=v.windowPosition(),m=b.scrX+c,h=b.scrY+d):a.browserIs("i")&&11!==a.getDocumentMode()?(h=m=0,c=function(a){m=a.screenX-a.clientX;h=a.screenY-a.clientY},document.documentElement.attachEvent("onmousemove",c),document.documentElement.fireEvent("onmousemove"),document.documentElement.detachEvent("onmousemove",c)):e.isDef(window.mozInnerScreenX)&&(m=s.round(window.mozInnerScreenX),h=s.round(window.mozInnerScreenY));return{scrX:m,
scrY:h}},c=function(){var a,b,c=d||v.getIeDimObj();e.isDef(window.innerWidth)?(a=window.innerWidth,b=window.innerHeight):c&&e.isDef(c.clientWidth)?(a=c.clientWidth,b=c.clientHeight,0===a&&0<c.offsetWidth&&(a=c.offsetWidth),0===b&&0<c.offsetHeight&&(b=c.offsetHeight)):window.frameElement&&e.isDef(window.frameElement.clientWidth)&&(a=window.frameElement.clientWidth,b=window.frameElement.clientHeight);return{width:a,height:b}},f=function(a,b){a=a||window;b=b||{top:0,left:0};for(var c,d=a.parent.document.getElementsByTagName("iframe"),
e=!1,n=0,r=d.length;n<r;n++)if(c=d[n],c.contentWindow==a){e=!0;break}e&&(c=v.getRect(c),b.left+=c.left,b.top+=c.top,a!==top&&f(a.parent,b));return b};return{calcDims:function(){var a={};try{a=e(b()).mixin(c())}catch(d){u.trigger("error",h.ERROR_CODES.GET_AD_DIMENSIONS)}return new H(a)},waitForBody:function(a){var b=setInterval(function(){document.body&&(d=v.getIeDimObj(),clearInterval(b),a())},50)}}},Ga=function(a,d,b,c,f,g,p,k){var m=function(a,b){if(b>=h.MAX_URL_LENGTH)return"";var c,d,f=[],g=function(a){return-1!==
a.key.indexOf("q")||-1!==a.key.indexOf("g")};c=e(a).map(function(a,b){if(g(b))return b});d=e(a).map(function(a,b){if(!g(b))return b});e(c.concat(d)).each(function(a,c){var d="adsafe_url="+c.val+"&adsafe_type="+c.key,e=f.join("&").length;d.length+e+b<=h.MAX_URL_LENGTH&&f.push(d)});return f.join("&")},q=function(a){var f=0,m=R.hashCode(l.asid),q="adsafe_jsinfo=",y=k.needsFlash()?{viewState:h.NA}:k.checkScreenLoc(!0),z="c:"+c.getCacheBustId()+",sl:"+y.viewState+",em:"+t.embedded+",fr:"+t.friendly,A=
b.on("postDts")&&w.getXHR2()?"p":"i",x=["pt:"+k.stringifyPingTimes()+(y.viewState!=h.NA?y.details:""),e(p.params()).toParams(),"id:"+l.asid];g.iterate(function(a,b){x.push(a+":"+b.output())});d.toString()&&x.push("e:"+d.toString());x.push(b.output());x.push("uf:"+(k.useFlash()?1:0));x.push("tt:"+l.mode);x.push("et:"+(s.now()-l.birthdate));x.push("uid:"+c.unq);x.push("v:9.1");x.push("sp:"+("true"===l.jsDoSplit?1:0));x.push("ct:"+t.getPageTime());x.push("dtm:"+A);x.push("mn:"+l.mn);x.push("gtpl:"+("true"===
l.getTpl?1:0));b.on("resolution")&&(x.push("wr:"+e(v.windowSize()).toArray().join(".")),x.push("sr:"+e(v.screenSize()).toArray().join(".")));-1===(""+m).indexOf(p.params().br.toUpperCase().charCodeAt(0))&&x.push("mf:"+m);var u=function(b){return q.length+a+b.length+5<=h.MAX_URL_LENGTH},C=function(a){if(a)return","+a};u(z)&&(q+=C(z),e(x).each(function(a,b){-1!==b.indexOf("id:")&&u(b)?(q+=C(b),c.impressionIsIdentifiable(!0)):u(b)?q+=C(b):f+=1}),C("sp:"+("true"===l.jsDoSplit?1:0)));return q+=",ov:"+
f};return{send:function(a){var b=f.baseUrl;try{b+=m(a,b.length)}catch(c){d.add(h.ERROR_CODES.IMPRESSION_URLS)}b+="&"===b.slice(-1)?"":"&";try{b+=q(b.length)}catch(e){d.add(h.ERROR_CODES.JSINFO),b+="adsafe_jsinfo=e:"+d.toString()}f.macroUrl&&(b+="&"===b.slice(-1)?"":"&",b+=f.macroUrl);try{f.sendImpression(b)}catch(g){__IntegralASDiagnosticCall("impsend",g,l)}}}},Da=function(a,d){return{init:function(b){a.jsonp(b,function(a){d.send(h.DT_CODES.THIRD_PARTY,void 0,!1,!0,{field:"tpiLookup",value:a})},!1,
"callback")}}},Aa=function(a,d,b){var c=function(a,b){return{time:a,task:b}},f=function(a,b){b=b||e.noop;return function(f){return e(f).map(function(e,f){var k=f/1E3;return new c(f,function(){var c;c="";1!==k&&(c+=k);c=l["_onInViewMRC"+c];d.send(a,k);b(c)})})}};return{getJob:function(a,b){return new c(a,b)},getPingJobs:f(h.DT_CODES.PING,function(c){"true"===l.useViewabilityNotification&&!b.skipAsFraudulent()&&c&&a.notify(c)}),getFullyInViewPingJobs:f(h.DT_CODES.FULLY_INVIEW),getPosInViewPingJobs:f(h.DT_CODES.POS_INVIEW)}},
na=function(){var a=function(a,c){-1!==a.indexOf(c+"&")&&(c+="&");return a.replace(c,"")},d=function(a,c,d){var e=a.indexOf("?");c=c+"="+d;if(-1===e)return a+"?"+c;e++;return a.slice(0,e)+c+"&"+a.slice(e)};return{wrap:function(b,c,e,g){var h="__IntegralAS_"+l.asid.replace(/\-/g,"")+"_"+s.round(1E4*Math.random()),k,m,q;g=g||"ias_callback";RegExp(g).test(b)&&(k=RegExp("("+g+"=)(.[^&]*)").exec(b)[0],m=k.split("=")[1],q=R.stringToFn(m),b=a(b,k));window[h]=function(a){c(a);e&&q&&q(a);window[h]=void 0};
return b=d(b,g,h)}}},ma=function(){var a=function(){return void 0!==window.mraid};return{isInView:function(){var d=h.NA;a()&&void 0!==window.mraid.isViewable&&(d=window.mraid.isViewable()?h.IN_VIEW:h.OUT_OF_VIEW);return d},getDetectionMethod:function(){return a()?h.DETECTION_METHODS.MOBILE:h.NA},isMobileApp:function(){return a()}}},Ea=function(a,d,b,c){var f={jss:{isFW:!0,nodeType:"script"},jsi:{isFW:!0,nodeType:"iframe"},jload:{impressionMethod:function(a){d.send(a,function(){u.trigger("sendDiag")},
!b.on("postMon"))}},bapi:{impressionMethod:function(b){d.jsonp(b,a.enabled?a.callback:e.noop,a.enabled?!0:!1)}},jsapi:{isFW:!0,impressionMethod:function(b){d.jsonp(b,a.enabled?a.callback:e.noop,a.enabled?!0:!1)}},jsvid:{impressionMethod:function(a){u.on("adImpression",function(){d.send(a,e.noop,!b.on("postMon"))})}},fwjsvid:{isFW:!0,processUrl:function(a){"false"===l.fwMonitoring&&(a=a.split("/"),a[3]="db2",a[4]="video",a=a.join("/"));return a},impressionMethod:function(a){"false"===l.fwMonitoring&&
d.jsonp(a,function(a){u.trigger("videoBlockResult",a)});u.on("adImpression",function(){d.send(a,void 0,!0)})}},jspix:{nodeType:"img"}};return new function(){var a=function(a){var b=-1===a.indexOf("?")?"?":"&";return a+b},b=f[l.mode],e=!!b.isFW,m=c&&l.mobFwUrl?l.mobFwUrl:e?l.adsafeSrc:l.requrl+"?"+l.reqquery,h=m.indexOf("BEGIN__ADSAFE"),n=-1!==h,r=n?m.slice(h):"",a=n?m.slice(0,h):a(m);return{isFW:e,baseUrl:a,macroUrl:r,sendImpression:function(a){a=b.processUrl?b.processUrl(a):a;b.nodeType?d.addNode(b.nodeType,
a):b.impressionMethod(a)}}}},La=function(a,d){var b,c=l.mtCell,f=l.mtSample,g=0,p=0,k=[],m=null,q=null,n,r=function(a){try{var b=s.now()-m;g+=b;w.removeEvent("mousemove",B);k.push("{ht:"+g+",mm:{"+e(n).toParams()+"}}");d.addItem({output:"{cs:"+c+",sr:"+f+",ec:"+k.length+",me:["+k.slice(-10).join(",")+"]}"},"mt",{type:h.DT_CODES.UNLOAD})}catch(l){}},u=function(a){try{g=0,n={},m=s.now(),w.addEvent(b,"mousemove",B)}catch(c){}},B=function(d){var g,m,k,h,l,r,B;try{null===q&&(q=b&&e.isDef(d.clientX)&&e.isDef(d.clientY));
if(q&&0===p%f&&(l=a.calcDims(),-1!==l)){B=s.ceil(l.width/c);var u=d.clientX,D=d.clientY;k=t.embedded?u:u-l.x;h=t.embedded?D:D-l.y;g=s.floor(k/c);m=s.floor(h/c);r=g+m*B;n[r]?n[r]++:n[r]=1}p++}catch(v){}};return{init:function(){var c=setInterval(function(){try{a.isAdDetected()&&(b=a.getOriginatingElement(),w.addEvent(b,"mouseenter",u),w.addEvent(b,"mouseleave",r),clearInterval(c))}catch(d){}},250)}}},s={execAtEndOfThread:function(a){setTimeout(a,0)},now:function(){return(new Date).getTime()},random:function(){return Math.random()},
round:function(a){return Math.round(a)},ceil:function(a){return Math.ceil(a)},floor:function(a){return Math.floor(a)},getWindow:function(){return window}},ja=function(a){var d={},b=s.now(),c=!0,f=new O,g=t.friendly&&a.on("blur")&&window.top.document&&e.isFunction(window.top.document.hasFocus);a=function(){var a=function(){b=s.now();window.webkitRequestAnimationFrame(a)};window.webkitRequestAnimationFrame(a);setInterval(function(){var a=100<s.now()-b;c!==a&&(c=a,f.run(a))},100)};var h=function(){var a=
null;e.isDef(document.hidden)?a=document.hidden:e.isDef(document.mozHidden)?a=document.mozHidden:e.isDef(document.msHidden)?a=document.msHidden:e.isDef(document.webkitHidden)&&(a=document.webkitHidden);if(null!==a){var b=a;c!==b&&(c=b,f.run(b))}return a};d.onHiddenChange=function(a){f.push(a)};d.isHidden=function(){return g&&!window.top.document.hasFocus()||h()};null===h()&&e.isDef(window.webkitRequestAnimationFrame)&&(a(),d.isHidden=function(){return c});return d},ka=function(){var a=function(a){for(var c in a)if(a.hasOwnProperty(c)){var d=
a[c];(""===d||"null"===d||"undefined"===d||null===d||e.isUndef(d))&&delete a[c]}return a},d=function(a){var c={},d,g;for(g in a)a.hasOwnProperty(g)&&(d=a[g],e.isUndef(c[d])?c[d]=g:c[d]+=g);a={};for(g in c)c.hasOwnProperty(g)&&(d=c[g],a[d]=g);return a};return{detectTopURL:function(){var b=function(){var a={g:"",q:""};try{a.q=window.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.location.href}catch(b){var c=b.message,c=c.substring(c.lastIndexOf("<")+1,c.lastIndexOf(">")),d;if(d=
e.isDef(c))if(d=!1,e.isDef(window.navigator)&&e.isDef(window.navigator.userAgent)){var f=window.navigator.userAgent.match(/Firefox\/([\.0-9]+)/);null!==f&&2==f.length&&(f=f[1].split("."),3==parseInt(f[0],10)&&6>=parseInt(f[1],10)&&(3==f.length?13>=parseInt(f[2],10)&&(d=!0):d=!0))}d&&(a.g=c)}return a},c={};try{c.a=encodeURIComponent(top.location.href)}catch(f){}try{c.b=encodeURIComponent(parent.location.href)}catch(g){}if(t.embedded){try{c.c=encodeURIComponent(parent.document.referrer)}catch(h){}try{c.e=
encodeURIComponent(window.document.referrer)}catch(k){}}try{"jsi"!==l.mode&&(c.d=encodeURIComponent(window.location.href))}catch(m){}try{c.f=encodeURIComponent(l.jsref)}catch(q){}try{var n=b();c.g=encodeURIComponent(n.g);c.q=encodeURIComponent(n.q)}catch(r){}var c=a(c),c=d(c),b=[],s;for(s in c)c.hasOwnProperty(s)&&b.push({key:s,val:c[s]});b.sort(function(a,b){return a.val.length>b.val.length?1:a.val.length<b.val.length?-1:0});return b}}},Na=function(a){return{hash:function(){for(var d=0,b=a.length,
c=[],f;d<b;d++)f=a[d].filename.replace(/\.plugin$/,""),f=R.hashCode(f),f=e.toBase(f,62).slice(-4),c.push(f);return c},decode:function(d){var b,c;b=s.floor(s.random()*d.length);c=encodeURIComponent(a[b].filename.replace(/\.plugin$/,""));return[d[b],c]}}},ga=function(a){var d=!1;return{measure:function(b){(d=0===b.rsa)&&l._onSuspicious&&a.trigger("notify",l._onSuspicious)},skipAsFraudulent:function(){return d}}},la=function(){var a=[],d={},b={sl:"n",gsl:"gn",fsl:"fn"},c=0,f,g,l={i:0,o:0,n:0,pp:0,pm:0,
gpp:0,gpm:0,gi:0,go:0,gn:0,fi:0,fo:0,fn:0},k=function(a){var b={},c=a.winDimensions,d=a.adDimensions;e.isDef(c)&&c.hasValidDims()&&(b.wc=c);e.isDef(d)&&d.hasValidDims()&&(b.ac=d,b.am=a.method,b.cc=a.containerDimensions);e({piv:"percentInView",obst:"obstructed",th:"tabHidden",reas:"reason",cmps:"adCompCount"}).each(function(c,d){var f=a[d];e.isDef(f)&&(b[c]=f)});c=e(b).toParams();return""===c?"":","+c},m=function(a,b){var c=new Va(b);return d[a]=c},q=function(a,b){return(b||"")+{inView:"i",outOfView:"o",
na:"n",partialViewMinus:"pm",partialViewPlus:"pp"}[a]},n=function(){e(b).each(function(b,d){l[d]+=a.length?g-c:g});c=g},r=function(c){a.length&&n();e(c).each(function(a,c){var d=b[a];d!==c&&"n"===d&&(l[c]+=l.n);b[a]=c});a.length||n()},s=function(a){var b,c=a.adDimensions.getRounded();b=k(a);var f={sl:q(a.viewState),fsl:q(a.fState||h.NA,"f"),gsl:q(a.gState||h.NA,"g")};g=t.getTagTime();r(f);f.t=g;b=e({toString:function(){e(d).each(function(a,b){b.fastForward()});return"{"+e(f).toParams()+this.details+
this.breakdowns+"}"},details:b,breakdowns:{piv:[],as:[],toString:function(){var a,b=function(a,b){return b.duration+"~"+b.state};a=""+("piv:["+e(this.piv).stringify(b)+"]");a+=",as:["+e(this.as).stringify(b)+"]";return",bkn:{"+a+"}"}},isInView:function(){return-1!==(h.IN_VIEW+"|"+h.PARTIAL_VIEW_PLUS).indexOf(a.viewState)},isFullyInView:function(){var b=a.useCocoa?a.fullPercentInView:a.percentInView;return this.isInView()&&100===b}}).mixin(f);e(b).mixin(a);b.width=c.width;b.height=c.height;return b};
(function(){m("piv",function(a){var b,c=a.percentInView,d=[1,25,30,50,75];100===c||0===c?b=c:(e(d).each(function(a,f){e.isUndef(b)&&c<f&&(b=d[a-1])}),e.isUndef(b)&&(b=d[d.length-1]));return b});m("as",function(a){a=a.adDimensions.getRounded();return a.width+"."+a.height})})();return{fastForward:function(){g=t.getTagTime();n()},registerLocation:function(c){var g,m=!1;b.sl==q(c.viewState)&&a.length?(g=new s(c),a[a.length-1].details=g.details):(g=new s(c),a.push(g),f=c.viewState,m=!0);u.trigger("newScreenEvent",
g);e(d).each(function(b,c){-1!=="piv|as".indexOf(b)?(m&&c.clear(),c.addState(g),a[a.length-1].breakdowns[b]=c.get()):c.addState(g)});return g},stringify:function(b){var c="";a.length&&(c=e({slTimes:"{"+e(l).toParams()+"}",slEvents:"["+a.slice(-b).join(",")+"]",slEventCount:a.length}).toParams());return c},createViewabilityTracker:m,getCurrentLoc:function(){return q(f)}}},Ja=function(a,d){var b={moPub:"mopb",adMob:"admb"},c={url:"u",ua:"a",j:"j"},f={url:function(a){return-1!==d.getWindow().location.href.indexOf(a)},
ua:function(b){var c=a.getUserAgent();return c&&-1!==c.indexOf(b)},j:function(a){return e.isDef(d.getWindow()[a])}},g=function(a,b){var d;(0,f[a])(b)&&(d=c[a]);return d},h=e({moPub:{url:"applewebdata"},adMob:{url:"pubads.g.doubleclick.net",ua:"afma-sdk",j:"AFMA_AddEventListener"}}).map(function(a,c){var d,f=e(c).map(g);f.length&&(d=b[a]+"*"+f.join(""));return d}).join(".");h&&u.trigger("addOutputItem",{output:function(){return h}},"sdk")},Ha=function(a){var d=l.asid,b=[0,1,4],c,f=function(){var a=
setInterval(function(){window.postMessage({asid:d,ksca:"acsk",sender:"main"},"*")},50);window.addEventListener("message",function(c){c=c.data;"acsk"===c.ksca&&c.asid===d&&"main"!==c.sender&&("ack"===c.type&&clearInterval(a),"complete"===c.type&&(c.timeReturned=s.now(),g(c)),b.length&&(c=b.shift(),window.postMessage(p(c),"*")))})},g=function(b){var c=-5-0.1*b.targets,d=h.DT_CODES.SCA;b="{"+e(b).stringify(function(a,b){var c;0===a.indexOf("time")?c=a+":"+b:"resultList"===a&&(c="rl:"+e(b).map(function(a,
b){return"{"+e(b).toParams()+"}"}).join("."));return c})+"}";a.trigger("addOutputItem",{output:b},"sc",{type:d});a.trigger("sendDt",d,c)},p=function(){var a=0,b=d.replace("-",""),e=b.substr(-6);return function(f){for(var g=c,h=s.now(),l=f,p=[];l--;)p.push(b.substr(++a,3));return{scaUrl:g,targets:f,timeBegun:h,src:e,targetList:p,asid:d,ksca:"acsk",sender:"main",cap:1E6}}}();return{load:function(){if(!e.isUndef(window.Worker)&&!e.isUndef(window.Blob)){var b=new K;b.sub("static");b.master(b.master().split(":")[0]);
b.path("sca.js");c=b.toString();a.trigger("exec",c);f()}}}},R={rot:function(a){return a.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)})},hashCode:function(a){var d=0,b,c,e;if(0===a.length)return d;b=0;for(e=a.length;b<e;b++)c=a.charCodeAt(b),d=(d<<5)-d+c,d|=0;return d},stringToFn:function(a){var d,b=window,c=a.split(".");for(a=0;a<c.length;a++)if(d=b,b=b[c[a]],e.isUndef(b)||a===c.length-1&&!e.isFunction(b))return!1;return function(){b.apply(d,
arguments)}}},wa=function(a,d,b,c,f){var g=h.OUT_OF_VIEW,p,k=function(){var b;if(p)return p;var c=function(b,c){var d=c["IASid"+a],f=e.isFunction(d);f&&d.call(c,a);return f};b=e(document.getElementsByTagName("object")).toArray();b=e(b).find(c);b||(b=e(document.getElementsByTagName("embed")).toArray(),(b=e(b).find(c))||__IntegralASDiagnosticCall("novidnode",{},l));return p=b};b.on("videoBlockResult",function(b){var c=k(),d=!1,f="blockAd"+a;"failed"===b.action&&(d=!0);if(c&&e.isDef(c.blockAd))c.blockAd(d);
else if(c&&e.isDef(c[f]))c[f](d)});(function(){var e=!1,k=!1;d.on("hundredpct")&&l.use100v&&(new Xa(b,c)).init();w.addEvent(window,"message",function(c){var d={};try{d=JSON.parse(unescape(c.data))}catch(l){d={}}d.recordType="video";d.id===a&&(c=d.messageType,-1!=="showAd|adStarted|adVideoStart|adVideoStarted|resumeAd".indexOf(c)?(e=!0,g=k?h.IN_VIEW:!1):-1!=="adVideoComplete|adStopped|stopAd|pauseAd".indexOf(c)?(e=!1,g=h.OUT_OF_VIEW):"resizeAd"===c&&("fullscreen"===d.viewMode?(k=!0,g=e?h.IN_VIEW:h.OUT_OF_VIEW):
(k=!1,g=e?!1:h.OUT_OF_VIEW)),f.addRecord(d),b.trigger(c,d))})})();return{findAdNode:k,getVersion:function(){var a=k();return a?a.getVersion():-1},getViewStateOverride:function(){return g}}},va=function(a){var d=[],b=function(b){var d=e({t:b.time-l.birthdate,tp:b.messageType,vid:b.id,sl:a.getCurrentLoc()}).mixin(b.eventData);return e({toString:function(){return"{"+e(d).toParams()+"}"}}).mixin(d)};return{getEvents:function(){return d},addRecord:function(a){a=new b(a);d.push(a)},stringify:function(){return"{"+
e({vEventCount:d.length,vEvents:"["+d.join(",")+"]"}).toParams()+"}"}}},Fa=function(a,d,b,c,f,g,p,k,m,q,n,r,u,v,y){var z,A,x,E,C=0,N=0,J,K=-1!==l.mode.indexOf("jsvid"),R=n.isMobileApp(),O=K?200:100,F=l.mobOrTab,ea=!F&&c.on("recordalternate"),G=c.on("forcecocoa"),I=a.getDocumentMode(),I=a.browserIs("g")||a.browserIs("i")&&(9===I||10===I)&&c.on("rattie"),aa=t.friendlyIframe&&G||t.xDomainIframe&&I&&G||t.xDomainIframe&&!I,L=!F&&aa&&c.on("cocoapuffs"),P=!1,Q=new Wa(10),M=[K&&c.on("videotwoseconds")?2E3:
1E3,5E3,15E3];c.on("everySecond")&&(M=[1E3,2E3,3E3,4E3,5E3,6E3,7E3,8E3,9E3,1E4,11E3,12E3,13E3,14E3,15E3]);var S=e(M).map(function(a,b){return b/1E3}).join("-"),Y=new ca(1E3),fa=new U(q.getPingJobs(M));if(c.on("hundredpct")&&l.use100v)var Z=new ca(1E3),W=new U(q.getFullyInViewPingJobs(M));if(c.on("tabHiddenDtCall"))var $=new ca(1E3),X=new U(q.getPosInViewPingJobs([M[0]]));var V=function(k){try{Q.start();var p,q,t,w,F,G;t=u.collect();var I=function(){V();c.on("viewabilityready")&&d.send(h.DT_CODES.VIEWABILITY_READY)};
ea&&(t.gState=t.viewState);if(L){z=z||new ba(T,t.adDimensions,I,c,r,a,b)||{};w=z.checkViewable();c.on("hundredpct")&&l.use100v&&(E=E||new Ta(Sa,t.adDimensions,I,a,c,f,m,r)||{},F=E.checkViewable(),t.fullPercentInView=F.pct,t.useCocoa=L);if(1!==t.tabHidden||w.str===h.NA)t.viewState=w.str;t.percentInView=w.pct;c.on("unreliabilityDetection")&&(x=x||new ba(T,H({height:0,width:-2E4}),e.noop,c,r,a)||{},G=x.checkViewable(),G.str!==h.OUT_OF_VIEW&&(N+=1),C+=1,m.addItem({output:N+"/"+C},"fu"))}else aa&&(t.viewState=
h.NA,t.percentInView=-1);ea&&(A||k||(A=L?z:new ba(T,t.adDimensions,e.noop,c,r,a,f)),t.fState=k?h.NA:A.checkViewable().str);if(K){if(q=y.getViewStateOverride()){if(q===h.OUT_OF_VIEW){var J=t.reason?t.reason.split("."):[];J[J.length]=h.OUT_OF_VIEW_REASONS.VIDEO;t.reason=J.join(".")}t.viewState=q}}else R&&(t.viewState=n.isInView());p=v.registerLocation(t);c.on("hundredpct")&&l.use100v&&(p.isFullyInView()?(Z.mark(),W.doEligibleJobs(Z.getTotalTime()),!c.on("zeroPing")||P||k||(d.send(h.DT_CODES.FULLY_INVIEW,
0),P=!0)):Z.stop());p.isInView()?(Y.mark(),fa.doEligibleJobs(Y.getTotalTime())):Y.stop();var O=fa.getNextJob();O&&O.time===M[0]&&c.on("tabHiddenDtCall")&&(t.posViewState===h.IN_VIEW||t.posViewState===h.PARTIAL_VIEW_PLUS?($.mark(),X.doEligibleJobs($.getTotalTime())):$.stop());Q.stop();var S=s.round(Q.getTime()/Q.getCount());m.addItem({output:S},"lt",{type:h.DT_CODES.UNLOAD});return p}catch(U){g.trigger("error",h.ERROR_CODES.CHECK_SCREEN_LOC)}},da=function(a){J=!0;var b=!1;a=function(){b||(b=!0,d.send(h.DT_CODES.VIDEO_EVENTS))};
p.impressionIsIdentifiable()&&(V(),setInterval(V,O),g.on("adStopped",a),g.on("adVideoComplete",a),w.addEvent(window,"beforeunload",d.unload,!1),K&&w.addEvent(window,"beforeunload",a,!1))};return{checkScreenLoc:V,init:function(){"true"===l.allowViewability&&e.isFunction(document.addEventListener)?(J=!1,"complete"==document.readyState||"loaded"==document.readyState||"interactive"==document.readyState?s.execAtEndOfThread(da):document.addEventListener("DOMContentLoaded",da,!1)):k.waitForBody(da)},needsFlash:function(){return aa},
readyFired:function(){return J},useFlash:function(){return L},stringifyPingTimes:function(){return S}}};try{Oa()}catch(Ya){__IntegralASDiagnosticCall("main",Ya,l)}};try{__IntegralASConfig.initialize(__IntegralASConfig)}catch(err$$11){__IntegralASDiagnosticCall("initialize",err$$11,__IntegralASConfig)};
