window.Backplane=window.Backplane||{"channelByBus":{},"config":{},"initialized":false,"subscribers":{},"awaiting":{"since":0,"until":0,"queue":[]},"intervals":{"min":5,"frequent":5,"regular":300,"slowdown":120}};
Backplane.init=function(config){config=config||{};if(this.initialized||!config.serverBaseURL||!config.busName)return false;this.initialized=true;this.timers={};this.config=config;this.channelByBus=this.getCookieChannels();this.config.customChannelName=config.channelName;this.config.channelName=this.getChannelName();this.config.serverBaseURL=this.normalizeURL(config.serverBaseURL);this.config.channelID=this.generateChannelID();this.request();return true};
Backplane.subscribe=function(callback){if(!this.initialized)return false;var id=(new Date).valueOf()+Math.random();this.subscribers[id]=callback;return id};Backplane.unsubscribe=function(subscriptionID){if(!this.initialized||!subscriptionID)return false;delete this.subscribers[subscriptionID]};Backplane.getChannelID=function(){if(!this.initialized)return false;return this.config.channelID};Backplane.expectMessages=function(types){this.expectMessagesWithin(60,types)};
Backplane.expectMessagesWithin=function(interval,types){if(!this.initialized||!interval)return false;this.awaiting.since=this.getTS();this.awaiting.interval=interval;this.awaiting.nonstop=!types;if(types){types=typeof types=="string"?[types]:types;this.awaiting.queue.push(types)}var until=this.awaiting.since+interval;if(until>this.awaiting.until)this.awaiting.until=until;this.request()};
Backplane.generateChannelID=function(){return this.config.serverBaseURL+"/bus/"+this.config.busName+"/channel/"+this.config.channelName};Backplane.getChannelName=function(){if(!this.initialized)return false;if(this.config.customChannelName)return this.config.customChannelName;if(!this.channelByBus[this.config.busName]){this.channelByBus[this.config.busName]=(new Date).valueOf().toString()+Math.random().toString().substr(2,5);this.setCookieChannels()}return this.channelByBus[this.config.busName]};
Backplane.getTS=function(){return Math.round((new Date).valueOf()/1E3)};Backplane.getCookieChannels=function(){var match=(document.cookie||"").match(/backplane-channel=(.*?)(?:$|;)/);if(!match||!match[1])return{};var channelByBus={};var parts=match[1].split("|");for(var i=0;i<parts.length;i++){var m=parts[i].split(":");channelByBus[decodeURIComponent(m[0])]=decodeURIComponent(m[1])}return channelByBus};
Backplane.setCookieChannels=function(){var parts=[];for(var i in this.channelByBus)if(this.channelByBus.hasOwnProperty(i))parts.push(encodeURIComponent(i)+":"+encodeURIComponent(this.channelByBus[i]));var d=new Date;d.setFullYear(d.getFullYear()+5);document.cookie="backplane-channel\x3d"+parts.join("|")+";expires\x3d"+d.toGMTString()+";path\x3d/"};
Backplane.resetCookieChannel=function(){delete this.channelByBus[this.config.busName];this.setCookieChannels();this.config.channelName=this.getChannelName();this.config.channelID=this.generateChannelID()};Backplane.normalizeURL=function(rawURL){return rawURL.replace(/^\s*(https?:\/\/)?(.*?)[\s\/]*$/,function(match,proto,uri){return(proto||"https://")+uri})};
Backplane.calcTimeout=function(){var timeout,ts=this.getTS();if(ts<this.awaiting.until){if(!this.awaiting.nonstop&&!this.awaiting.queue.length){this.awaiting.until=ts;return this.calcTimeout()}var relative=ts-this.awaiting.since;var limit=this.intervals.frequent-this.intervals.min;timeout=this.intervals.min+Math.round(limit*relative/this.awaiting.interval)}else if(ts<this.awaiting.until+this.intervals.slowdown){var relative=ts-this.awaiting.until;var limit=this.intervals.regular-this.intervals.frequent;
timeout=this.intervals.frequent+Math.round(limit*relative/this.intervals.slowdown)}else{timeout=typeof this.since=="undefined"?0:this.intervals.regular;this.awaiting.nonstop=false}return timeout*1E3};
Backplane.request=function(){var self=this;if(!this.initialized)return false;this.stopTimer("regular");this.stopTimer("watchdog");this.timers.regular=setTimeout(function(){self.timers.watchdog=setTimeout(function(){self.request()},5E3);var script=document.createElement("script");script.type="text/javascript";script.charset="utf-8";script.src=self.config.channelID+"?callback\x3dBackplane.response"+(self.since?"\x26since\x3d"+encodeURIComponent(self.since):"")+"\x26rnd\x3d"+Math.random();var container=
document.getElementsByTagName("head")[0]||document.documentElement;container.insertBefore(script,container.firstChild);script.onload=script.onreadystatechange=function(){var state=script.readyState;if(!state||state==="loaded"||state==="complete"){script.onload=script.onreadystatechange=null;if(script.parentNode)script.parentNode.removeChild(script)}}},this.calcTimeout())};
Backplane.response=function(messages){var self=this;this.stopTimer("watchdog");messages=messages||[];var since=messages.length?messages[messages.length-1].id:this.since;if(typeof this.since=="undefined")messages=[];this.since=since||"";for(var i=0;i<messages.length;i++){for(var j in this.subscribers)if(this.subscribers.hasOwnProperty(j))this.subscribers[j](messages[i].message);var queue=[];for(var k=0;k<this.awaiting.queue.length;k++){var satisfied=false;for(var l=0;l<this.awaiting.queue[k].length;l++)if(this.awaiting.queue[k][l]==
messages[i].message.type)satisfied=true;if(!satisfied)queue.push(this.awaiting.queue[k])}this.awaiting.queue=queue}this.request()};Backplane.stopTimer=function(name){var timer=this.timers[name];if(timer)clearTimeout(timer)};