
define(['jquery','underscore','klass'],function($,_,klass){var TickerSearch=klass({tickerInput:undefined,exchangeInput:undefined,container:undefined,horizontalAlignment:undefined,smartboxTable:undefined,lastServerQuery:undefined,lastRawQuery:undefined,highlightedSmartboxRow:undefined,initialize:function(tickerInput,options){this.tickerInput=$(tickerInput);this.exchangeInput=$(options.exchangeInput);this.container=options.resultsContainer;this.horizontalAlignment=options.horizontalAlignment;this.resultsTable=options.resultsTable;this.form=$(this.tickerInput).closest("form")[0];this.themeName=options.themeName||(typeof themeName!='undefined'&&themeName)||this.themeNames.DailyFinance;this.templateSettings={interpolate:/\{\{(.+?)\}\}/g};_.templateSettings=this.templateSettings;var defaults={submitOnSelection:false,submitButtonID:"",smartBoxID:"",moreText:"View all results for",moreLink:null};this.options=$.extend(defaults,options);if(this.options.submitButtonID&&this.options.smartboxID){this.submitButtonID=this.options.submitButtonID;this.smartboxID=this.options.smartboxID;}
$(this.tickerInput).keydown(_.bind(this.onInputKeydown,this));$(this.tickerInput).keyup(_.bind(this.onInputKeyup,this));this.stoppedKeys=[this.keycodes.KEYALT,this.keycodes.KEYTAB];this.ajaxSequence=0;$(document).on('click','*:not(#ticker-smartbox)',this.hideSmartboxTable.bind(this));},buildSmartboxTable:function(query,searchResults){if(this.smartboxTable){this.smartboxTable.remove();}
this.highlightedSmartboxRow=undefined;var keyword=query.toUpperCase();if(this.resultsTable){this.smartboxTable=$('<table></table>').attr(this.resultsTable);}else{this.smartboxTable=$('<table></table>').attr({'id':'fool-smartbox-results'});}
var lookupUrl=this.getLookupUrl(keyword);var tableContents=_.template(this.smartboxTableTemplate,{'query':keyword,'lookupText':this.options.moreText,'lookupUrl':lookupUrl,'tablerows':''},this.templateSettings);this.smartboxTable.append(tableContents);_.each(searchResults,function(result){this.createSmartboxTableRow(keyword,result)},this);this.positionTableOnPage();},positionTableOnPage:function(){if(this.smartboxTable){if(this.isNewslettersMobileView()){var mainContent=$("#main-content");$(this.smartboxTable).css({position:'absolute',top:(mainContent.offset().top-1),left:mainContent.offset().left,width:mainContent.width()});}
else{$(this.smartboxTable).css({position:'absolute',top:this.tickerInput.offset().top+this.tickerInput.innerHeight()});var horizontalOffset=typeof this.horizontalAlignment==='undefined'?{left:this.tickerInput.offset().left}:{right:$(window).width()-(this.tickerInput.offset().left+this.tickerInput.outerWidth())};$(this.smartboxTable).css(horizontalOffset);}
$(document.body).append(typeof this.container==='undefined'?this.smartboxTable:this.container.append(this.smartboxTable));}},isNewslettersMobileView:function(){var regEx=new RegExp("newsletters.fool.com");if(regEx.test(window.location.hostname)&&$("body").hasClass("mobileView")){return true;}
return false;},getLookupUrl:function(keyword){if(this.options.moreLink){return this.options.moreLink.replace("TERM",keyword);}
var host=document.location.host.toLowerCase();if(host.indexOf('dailyfinance.com')!==-1){return'http://www.dailyfinance.com/lookup/'+encodeURIComponent(keyword);}
return'/quote/jump?ticker-input='+encodeURIComponent(keyword);},createSmartboxTableRow:function(query,searchResult){var ticker=searchResult.symbol;var companyName=searchResult.company_name;var exchangeCode=searchResult.exchange;var countryCode=searchResult.country;var mungedTicker=ticker.replace(query,"<strong class=\"match\">"+query+"</strong>");companyName=companyName.toUpperCase();if(companyName.length>100){companyName=companyName.substring(0,99)+'\u2026';}
companyName=companyName.replace(query,"<strong class=\"match\">"+query+"</strong>");var contents=_.template(this.smartboxTableRowTemplate,{'ticker':mungedTicker,'companyname':companyName,'exchange':exchangeCode,'country-code':countryCode,'query':query},this.templateSettings);var row=$('<tr class="predictive-search-results-result"></tr>').attr({'data-ticker':ticker,'data-exchange-code':exchangeCode,'data-country-code':countryCode});this.smartboxTable.children('tbody').append(row);row.append(contents);row.on('click',_.bind(this.onSmartboxRowClick,this));row.on('mouseenter',_.bind(this.onSmartboxRowMouseover,this));row.on('mouseleave',_.bind(this.onSmartboxRowMouseout,this));if(this.options.submitOnSelection){row.on('click',_.bind(this.submitForm,this));}
return row;},resultShouldBeHidden:function(searchResult){if(this.lastRawQuery.indexOf(":")===-1){return false;}
var countryCode=searchResult["cc"];return(countryCode&&countryCode==="USA");},loadAutoCompleteResults:function(query){var self=this;var callbackName='_predictiveSearch_'+query.replace(/[^a-zA-Z0-9_]/g,'_').toLowerCase();var sequence=++self.ajaxSequence;var searchPromise=$.ajax({type:'GET',url:'//j.foolcdn.com/tmf/predictivesearch',data:{term:query,domain:self.themeName},dataType:'jsonp',jsonp:'callback',jsonpCallback:callbackName,crossDomain:true,cache:true});searchPromise.done(function(data){if(sequence>=self.ajaxSequence){self.lastRawQuery=query;self.lastServerQuery=self.normalizeQuery(query);self.processAutoCompleteResultsFromSolr(data);}});searchPromise.fail(function(data){if(typeof console!=="undefined"&&console.log){console.log('error',data);}});},processAutoCompleteResultsFromSolr:function(response){var response=response.response;if(response.numFound>0){this.searchResults=response.docs;this.buildSmartboxTable(this.lastServerQuery,this.searchResults);}else{this.hideSmartboxTable();}},enableSubmit:function(){$(this.submitButtonID).enable();},hideSmartboxTable:function(){if(!this.smartboxTable){return;}
this.highlightedSmartboxRow=undefined;this.smartboxTable.remove();this.smartboxTable=undefined;this.lastRawQuery=undefined;this.lastServerQuery=undefined;},smartboxIsPresent:function(){return this.smartboxTable&&this.smartboxTable.is(':visible');},onInputKeydown:function(event){var keyCode=event.keyCode;if(_.indexOf(this.stoppedKeys,keyCode)!==-1){event.stopPropagation();return false;}
if(keyCode===this.keycodes.KEYENTER){this.enterSelectedSmartboxRow(this.highlightedSmartboxRow);}
else if(keyCode===this.keycodes.KEYDOWN){event.stopPropagation();this.highlightNextSmartboxRow();}
else if(keyCode===this.keycodes.KEYUP){event.stopPropagation();this.highlightPreviousSmartboxRow();}
else if(keyCode===this.keycodes.KEYESC){event.stopPropagation();this.hideSmartboxTable();return false;}},onInputKeyup:function(event){if(event.keyCode===this.keycodes.KEYESC){event.stopPropagation();return false;}
if(event.keyCode===this.keycodes.KEYENTER){return false;}
this.smartboxQueryChanged();},onSmartboxRowClick:function(event){var row=this.getTableRowForEvent(event);this.enterSelectedSmartboxRow(row);},submitForm:function(event){this.form.submit();},onSmartboxRowMouseover:function(event){var row=this.getTableRowForEvent(event);this.highlightSmartboxRow(row);},onSmartboxRowMouseout:function(event){var row=this.getTableRowForEvent(event);row.removeClass('select').removeClass('selected');if(this.highlightedSmartboxRow===row){this.highlightedSmartboxRow=undefined;}},unhighlightSmartboxRows:function(){var highlightedRows=this.smartboxTable.children('tbody').children('tr.select');$.each(highlightedRows,function(i,row){$(row).removeClass('select').removeClass('selected');});},highlightSmartboxRow:function(row){this.unhighlightSmartboxRows();row.addClass('select').addClass('selected');this.highlightedSmartboxRow=row;},highlightNextSmartboxRow:function(){if(!this.smartboxIsPresent()){return;}
var rowToHighlight=this.getFirstSmartboxRow();if(this.highlightedSmartboxRow&&this.highlightedSmartboxRow.next().length){rowToHighlight=this.highlightedSmartboxRow.next();}
this.highlightSmartboxRow(rowToHighlight);},highlightPreviousSmartboxRow:function(){if(!this.smartboxIsPresent()){return;}
var rowToHighlight=this.getLastSmartboxRow();if(this.highlightedSmartboxRow&&this.highlightedSmartboxRow.prev().length){rowToHighlight=this.highlightedSmartboxRow.prev();}
this.highlightSmartboxRow(rowToHighlight);},getFirstSmartboxRow:function(){return this.smartboxTable.children('tbody').children('tr:first');},getLastSmartboxRow:function(){return this.smartboxTable.children('tbody').children('tr:last');},smartboxQueryChanged:function(){var currentQuery=this.tickerInput.val();var currentNormalizedQuery=this.normalizeQuery(currentQuery);if(this.lastServerQuery==currentNormalizedQuery){return;}
else if(!currentNormalizedQuery){this.hideSmartboxTable();return;}
this.loadAutoCompleteResults(currentQuery);},normalizeQuery:function(query){if(!query){return"";}
var normalizedQuery=query.toUpperCase().replace(/ /g,'');var colonPosition=normalizedQuery.indexOf(":");if(colonPosition!==-1){normalizedQuery=query.substring(0,colonPosition);}
return normalizedQuery;},extractTickerFromQuery:function(query){if(!query){return"";}
var normalizedQuery=query.toUpperCase().replace(/ /g,'');var queryLength=query.length;var colonPosition=normalizedQuery.indexOf(":");if(colonPosition!==-1){normalizedQuery=normalizedQuery.substring(colonPosition+1,queryLength);}
return normalizedQuery;},getTableRowForEvent:function(event){var elem=$(event.target);if(elem.prop('tagName').toUpperCase()==='TR'){return elem;}
return elem.closest('tr');},enterSelectedSmartboxRow:function(row){if(!row){return;}
var data=row.data();this.tickerInput.setValue(data.exchangeCode+":"+data.ticker);this.tickerInput.focus();this.hideSmartboxTable();},smartboxTableRowTemplate:'<td class="predictive-search-results-result-symbol sym">{{ticker}}</td>'+'<td class="predictive-search-results-result-company-name comp">{{companyname}}</td>'+'<td class="predictive-search-results-result-exchange exch"><span style="white-space: nowrap">{{exchange}}</span></td>',smartboxTableTemplate:'<tfoot><tr><td class="predictive-search-results-link" colspan="3"><a href="{{lookupUrl}}" id="view-all">{{lookupText}} \'{{query}}\'</a></td></tr></tfoot>'+'<tbody>'+'{{tablerows}}'+'</tbody>',keycodes:{KEYLEFT:37,KEYUP:38,KEYRIGHT:39,KEYDOWN:40,KEYENTER:13,KEYTAB:9,KEYBACKSPACE:8,KEYDELETE:46,KEYTAB:9,KEYALT:18,KEYESC:27},themeNames:{DailyFinance:'dailyfinance.com'},securityTypes:["","","","Preferred Stock","Warrant","Premium","Trust","Right","Warrant Right","Index","Future","Future Spread","Option","Equity Option","Index Option","Future Option","Fixed Income","Bond","Convertible Bond","Mortgage Backed","Government Bond","Corporate Bond","US Agency Bond","US Treasury Bill","US Treasury Coupon","Money Market","CD","Mutual Fund","Mutual Fund","Money Market Fund","Unit Inv. Trust Ph. 1","Unit Inv. Trust Ph. 2","Currency","Forex FRA","Forex Deposit","Forex Forward","Market Indicator","Fund","ETF","Loan","","Statistic"]});return TickerSearch;});