var ut_window,ut_document,ut_iframe="",ut_iframe_padding=ut_iframe_padding||20;top.location!=location?(ut_window=window.top,ut_document=parent.document):(ut_window=window,ut_document=document);
(function(a){a.DOMReady=function(){var b=[],c=!1,d=null,e=function(a,b){try{a.apply(this,b||[])}catch(c){d&&d.call(this,c)}},f=function(){c=!0;for(var a=0;a<b.length;a++)e(b[a].fn,b[a].args||[]);b=[]};this.setOnError=function(a){d=a;return this};this.add=function(a,d){c?e(a,d):b[b.length]={fn:a,args:d};return this};a.addEventListener?a.document.addEventListener("DOMContentLoaded",function(){f()},!1):function(){if(a.document.uniqueID||!a.document.expando){var b=a.document.createElement("document:ready");
try{b.doScroll("left"),f()}catch(c){setTimeout(arguments.callee,0)}}}();return this}()})(window);function ut_gatherOverlayElements(){var a=ut_document.getElementById("utOverlay"),b=ut_document.getElementById("utAdBackdrop"),c=ut_document.getElementById("utbanner"),d=ut_document.getElementById("ut_fp_ad_container");return[a,b,d,c]}function ut_closeFP(){var a=ut_gatherOverlayElements();if(null!=ut_document.getElementById("utOverlay"))for(var b=0;b<a.length;b++)a[b].parentNode.removeChild(a[b])}
function ut_loadFP(){var a=ut_document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href=UT_DELIVERY_URL_ROOT+"css/fullpage.css";a.media="screen";a.title="undertoneFullpage";ut_document.getElementsByTagName("head")[0].appendChild(a);ut_adHeight|=0;ut_adWidth|=0;var a=ut_document.getElementsByTagName("body")[0],b=ut_document.createElement("div");b.id="utOverlay";a.appendChild(b);""!=ut_bgimg&&(b.style.backgroundImage="url('"+ut_bgimg+"')");b.style.backgroundColor=ut_bgcolor;b=ut_document.createElement("div");
b.id="utAdBackdrop";b.style.padding="0 10px 10px";b.style.margin="0 0 0 "+(-1*(ut_adWidth/2+10)).toFixed()+"px";a.appendChild(b);a='<div id="aboutUndertone" style="display: block;"><div id="utLogo" style="display: block;">'+('<a href="'+ut_logourl+'" id="utImgLink" target="_blank" style="display: block;"><img src="'+ut_logoimg+'" id="utImg" style="display: block;"></a>');a+="</div>";a+='<div id="utMetaLinks" style="display: block;">';a+='<a href="'+ut_abouturl+'" id="utAboutLink" target="_blank" style="display: inline;">about this ad</a>';
a+='<span id="utPipe"> | </span>';a+='<span id="utMinimize" style="display: inline;">'+ut_closebtntext+"</span>";a+='<div id="utClear1" class="utClear"></div>';a+="</div>";a+='<div id="utClear2" class="utClear"></div>';a+="</div>";b.innerHTML=a;var a=ut_document.createElement("div"),c=300,b=function(){null!=ut_iframe.doc&&ut_iframe.doc.close()},c='<html><head><style type="text/css">a,img,body{margin:0px;padding:0px;border:none;background:transparent;}</style></head><body>'+ut_creative+"</body></html>";
ut_document.getElementById("utAdBackdrop").appendChild(a);a.id="ut_fp_ad_container";a.style.margin="0px 0px 0px 0px";a.style.padding="0px 0px 0px 0px";a.style.height=ut_adHeight+"px";a.style.width=ut_adWidth+"px";a.style.position="relative";a.style.background="#eee";a.style.overflow="hidden";a.innerHTML="";a.style.cssText="overflow:hidden;height:"+ut_adHeight+"px;width:"+ut_adWidth+"px;vertical-align:top";a.height=ut_adHeight;a.width=ut_adWidth;a.scrolling="no";a.align="left";ut_iframe=document.createElement("iframe");
a.appendChild(ut_iframe);ut_iframe.setAttribute("name","utbanner");ut_iframe.setAttribute("id","utbanner");ut_iframe.setAttribute("height",ut_adHeight);ut_iframe.setAttribute("width",ut_adWidth);ut_iframe.setAttribute("frameborder","0");ut_iframe.setAttribute("scrolling","no");ut_iframe.src="javascript:";ut_iframe.style.cssText="width:100%;height:100%;border:none;margin:0px;padding:0px;v-space:0;.h-space:0;vertical-align:top;";ut_iframe.marginwidth="0px";ut_iframe.marginheight="0px";ut_iframe.frameborder=
"0";ut_iframe.align="left";ut_iframe.height="100%";ut_iframe.width="100%";ut_iframe.vAlign="top";ut_iframe.doc=null;ut_iframe.contentWindow?(ut_iframe.doc=ut_iframe.contentWindow.document,ut_iframe.contentWindow.location.href=ut_iframe.src):ut_iframe.contentDocument?ut_iframe.doc=ut_iframe.contentDocument.document:ut_iframe.document&&(ut_iframe.doc=ut_iframe.document);ut_iframe.doc&&(ut_iframe.doc.open(),ut_iframe.doc.write(c),"Netscape"==window.navigator.appName&&-1<window.navigator.appVersion.indexOf("Trident")||
document.attachEvent&&!window.opera?(ut_iframe.style.width=ut_adWidth+ut_iframe_padding+"px",ut_iframe.style.height=ut_adHeight+ut_iframe_padding+"px",ut_iframe.style.backgroundColor="transparent",ut_iframe.height=ut_adHeight+ut_iframe_padding+"px",ut_iframe.width=ut_adWidth+ut_iframe_padding+"px",c=400):(ut_iframe.scrolling="no",ut_iframe.overflow="none",c=300),setTimeout(b,c));ut_document.getElementById("utMinimize").onclick=ut_closeFP;setTimeout("ut_closeFP()",1100*ut_minimizeDelay)}DOMReady.add(function(){ut_loadFP()});
