EBGVT="undefined"!=typeof EBGVT?EBGVT:{};EBGVT.Light=EBGVT.Light||{};EBGVT.Light.Infra=function(){};EBGVT.Light.Infra.isDefined=function(a){return"undefined"!=typeof a};EBGVT.Light.Infra.indexOfArray=function(a,b,c){for(var c=c||0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1};EBGVT.Light.Infra.getTimestamp=function(){var a=new Date;return parseInt(a.getHours()+1)+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds()+" "+a.getDate()+"."+parseInt(a.getMonth()+1)+"."+a.getFullYear()};
EBGVT.Light.Infra.getUrlParameter=function(a){var b="",c=EBGVT.Light.Infra.getWindowLocation().toString(),d=RegExp("[&,?]"+a+"=(.*)$","i");if((a=c.match(RegExp("[&,?]"+a+"=(.*)[&]","i"))||c.match(d))&&0<a.length)-1<a[1].indexOf("&")&&(a[1]=a[1].substr(0,a[1].indexOf("&"))),b=a[1];return b};EBGVT.Light.Infra.combinePaths=function(a,b){a=a||"";b=b||"";a&&"/"!=a[a.length-1]&&(a+="/");var c=a;b&&(c+=b);return c};
EBGVT.Light.Infra.isPageLoaded=function(){var a=!0;"complete"!=document.readyState&&"loaded"!=document.readyState&&"interactive"!=document.readyState&&(a=!1);return a};EBGVT.Light.Infra.addChildToPage=function(a,b,c,d){if("undefined"==typeof b||!b)b=document.body||document.getElementsByTagName("head")[0];this.isDefined(c)&&null!=c&&this.addEventListener(a,c,d);b.appendChild(a)};
EBGVT.Light.Infra.addEventListener=function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):(b="on"+b,a.attachEvent?a.attachEvent(b,c):b in a&&(a[b]=c))};EBGVT.Light.Infra.createScriptElement=function(a,b,c,d){try{var e=a.createElement(b);e.type=c;e.src=d;e.async=!1;return e}catch(f){}};
EBGVT.Light.Infra.addScriptElement=function(a,b){var c;if(b){if(c=b,0==c.childNodes.length){var d=document.createElement("div");d.style.display="none";b.appendChild(d)}}else c=document.head||document.documentElement;c.insertBefore(a,c.firstChild)};EBGVT.Light.Infra.getWindowLocation=function(){return window.location};EBGVT.Light.Infra.getRandomNumber=function(){try{var a=Math.random().toString();return a=a.substr(a.indexOf(".")+1)}catch(b){}};
EBGVT.Light.Infra.getAddInEyeDomain=function(a){var b="",c="",d=0,a=(a?a:window).document,a=a.referrer?a.referrer:a.location.href;try{a=a.toLowerCase(),7<=a.length&&"http://"==a.substr(0,7)?(c=a.substr(7),a.substr(0,7)):8<=a.length&&"https://"==a.substr(0,8)?(c=a.substr(8),a.substr(0,8)):c=a,d=c.indexOf("/"),0<d&&(c=c.substr(0,d)),b=c}catch(e){b=""}return b};
EBGVT.Light.Infra.createFriendlyIframe=function(a,b,c,d){a=(a?a:document).createElement("iframe");b&&a.setAttribute("id",b);a.style.display=c?"":"none";a.style.width=c?c+"px":"0px";a.style.height=d?d+"px":"0px";document.documentMode&&8>document.documentMode?(a.frameBorder=0,a.margin=0,a.marginWidth=0,a.marginHeight=0,a.scrolling="no"):(a.setAttribute("scrolling","no"),a.setAttribute("marginwidth","0"),a.setAttribute("marginheight","0"),a.setAttribute("frameborder","0"));return a};
EBGVT.Light.Infra.isIframeScriptable=function(a){try{this.ifrmDocument=a.contentWindow.document}catch(b){return!1}return!0};EBGVT.Light.Infra.enableIframeScriptable=function(a){if(a){a.setAttribute("data-isready","false");var b;b="javascript:document.write('<scr'+'ipt>\r"+('try{parent.document.domain;}catch(e){document.domain="'+document.domain+'";}\r');a.src=b+"parent.EBGVT.Light.Infra.friendlyIframeIsReadyCallback(window);\r</scr'+'ipt>\r');"}};
EBGVT.Light.Infra.friendlyIframeIsReadyCallback=function(a){for(var b=document.getElementsByTagName("iframe"),c=0;c<b.length;c++)try{if((b[c].contentWindow||b[c].contentDocument.window||b[c].window)==a){b[c].setAttribute("data-isready","true");break}}catch(d){}};
EBGVT.Light.Infra.writeToFriendlyIframe=function(a,b,c){if(document.documentMode&&7<document.documentMode&&"false"==a.getAttribute("data-isready"))setTimeout(function(){EBGVT.Light.Infra.writeToFriendlyIframe(a,b,c)},100);else{var c=this.isDefined(c)?c:!1,d;d=a.contentWindow?a.contentWindow.document:a.contentDocument&&a.contentDocument.document?a.contentDocument.document:a.contentDocument;d.write(b);c&&setTimeout(function(){d.close()},1E3)}};
EBGVT.Light.Infra.createUnfriendlyIframe=function(a,b){if(b&&!EBGVT.Light.Infra.isPageLoaded())this.logger&&this.logger.info("Adding unfriendly iframe in sync mode, url: "+a),document.write('<iframe src="'+a+'" style="display:none;width:0px;height:0px"></iframe>');else{this.logger&&this.logger.info("Adding unfriendly iframe in async mode, url: "+a);var c=document.createElement("iframe");c.setAttribute("src",a);c.style.display="none";EBGVT.Light.Infra.addChildToPage(c)}};
EBGVT.Light.Infra.getTopLevelReferrer=function(a){var b=null;try{if(a.top&&a.top.document&&a.top.document.referrer)b=a.top.document.referrer.toString();else throw Error("Unfriendly iframe");}catch(c){this.isDefined(a)&&a.document&&a.document.referrer&&(b=a.document.referrer.toString())}return b};EBGVT.Light.Infra.getTokenValueFromURL=function(a,b){var c=b.indexOf("?")?b.split("?")[1]:"";if(c)for(var c=c.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(e[0]==a)return e[e.length-1]}return null};
EBGVT.Light.Infra.urlAvailableLength=function(a){var b=8E3;EBGVT.Light.Infra.isOldIE()&&(b=2048);return b-a.length};EBGVT.Light.Infra.isOldIE=function(){var a=navigator.userAgent,b;if(-1!=(b=a.indexOf("MSIE"))){a=a.substring(b+5);if(-1!=(b=a.indexOf(";")))a=a.substring(0,b);if(-1!=(b=a.indexOf(" ")))a=a.substring(0,b);a=parseInt(""+a,10);isNaN(a)&&(parseFloat(navigator.appVersion),a=parseInt(navigator.appVersion,10));if(9>a)return!0}return!1};
EBGVT.Light.Infra.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array||!(a instanceof Object)&&"[object Array]"==Object.prototype.toString.call(a)||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&("[object Function]"==Object.prototype.toString.call(a)||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};EBGVT.JSON="JSON"in window&&window.JSON&&window.JSON.stringify&&window.JSON.parse?JSON:{};
(function(){function a(a){return 10>a?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=x[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,m,n,q,r=f,j,g=d[a];g&&"object"===typeof g&&"function"===typeof g.toJSON&&(g=g.toJSON(a));"function"===typeof k&&(g=k.call(d,a,g));switch(typeof g){case "string":return b(g);case "number":return isFinite(g)?""+g:"null";case "boolean":case "null":return""+
g;case "object":if(!g)return"null";f+=h;j=[];if("[object Array]"===Object.prototype.toString.apply(g)){q=g.length;for(e=0;e<q;e+=1)j[e]=c(e,g)||"null";n=0===j.length?"[]":f?"[\n"+f+j.join(",\n"+f)+"\n"+r+"]":"["+j.join(",")+"]";f=r;return n}if(k&&"object"===typeof k){q=k.length;for(e=0;e<q;e+=1)m=k[e],"string"===typeof m&&(n=c(m,g))&&j.push(b(m)+(f?": ":":")+n)}else for(m in g)Object.hasOwnProperty.call(g,m)&&(n=c(m,g))&&j.push(b(m)+(f?": ":":")+n);n=0===j.length?"{}":f?"{\n"+f+j.join(",\n"+f)+"\n"+
r+"}":"{"+j.join(",")+"}";f=r;return n}}if("function"!==typeof Date.prototype.toJSON)Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,h,x={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},k;if("function"!==typeof EBGVT.JSON.stringify)EBGVT.JSON.stringify=function(a,b,d){var e;h=f="";if("number"===typeof d)for(e=0;e<d;e+=1)h+=" ";else"string"===typeof d&&(h=d);if((k=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("EBGVT.JSON.stringify");
return c("",{"":a})};if("function"!==typeof EBGVT.JSON.parse)EBGVT.JSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&"object"===typeof g)for(e in g)Object.hasOwnProperty.call(g,e)&&(f=c(g,e),void 0!==f?g[e]=f:delete g[e]);return b.call(a,d,g)}var e;d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?c({"":e},""):e;throw new SyntaxError("EBGVT.JSON.parse");}})();EBGVT.BrowserDetector=function(){this.browserName=navigator.appName;this.fullVersion=""+parseFloat(navigator.appVersion);this.majorVersion=parseInt(navigator.appVersion,10);this._init()};EBGVT.BrowserDetector.Browser={InternetExplorer:"InternetExplorer",Chrome:"Chrome",Firefox:"Firefox",Opera:"Opera",Safari:"Safari"};
EBGVT.BrowserDetector.prototype={_init:function(){var a=navigator.userAgent,b,c;if(-1!=(c=a.indexOf("Opera"))){if(this.browserName=EBGVT.BrowserDetector.Browser.Opera,this.fullVersion=a.substring(c+6),-1!=(c=a.indexOf("Version")))this.fullVersion=a.substring(c+8)}else if(-1!=(c=a.indexOf("MSIE")))this.browserName=EBGVT.BrowserDetector.Browser.InternetExplorer,this.fullVersion=a.substring(c+5);else if(-1!=(c=a.indexOf("Chrome")))this.browserName=EBGVT.BrowserDetector.Browser.Chrome,this.fullVersion=
a.substring(c+7);else if(-1!=(c=a.indexOf("Safari"))){if(this.browserName=EBGVT.BrowserDetector.Browser.Safari,this.fullVersion=a.substring(c+7),-1!=(c=a.indexOf("Version")))this.fullVersion=a.substring(c+8)}else if(-1!=(c=a.indexOf("Firefox")))this.browserName=EBGVT.BrowserDetector.Browser.Firefox,this.fullVersion=a.substring(c+8);else if((b=a.lastIndexOf(" ")+1)<(c=a.lastIndexOf("/")))if(this.browserName=a.substring(b,c),this.fullVersion=a.substring(c+1),this.browserName.toLowerCase()==this.browserName.toUpperCase())this.browserName=
navigator.appName;if(-1!=(a=this.fullVersion.indexOf(";")))this.fullVersion=this.fullVersion.substring(0,a);if(-1!=(a=this.fullVersion.indexOf(" ")))this.fullVersion=this.fullVersion.substring(0,a);this.majorVersion=parseInt(""+this.fullVersion,10);if(isNaN(this.majorVersion))this.fullVersion=""+parseFloat(navigator.appVersion),this.majorVersion=parseInt(navigator.appVersion,10)}};EBGVT.Light.Logger=function(a){this._level=a;this.startNestingGroupNames=[];this.endNestingGroupNames=[]};
EBGVT.Light.Logger.DebugMode="mmdebug";EBGVT.Light.Logger.LoggerLevels={NONE:0,ERROR:1,INFO:2,WARN:3,DEBUG:4};
EBGVT.Light.Logger.prototype={setLevel:function(a){this._level=a},timestamp:!1,debug:function(a){this._reportToLog(EBGVT.Light.Logger.LoggerLevels.DEBUG,arguments)},info:function(a){this._reportToLog(EBGVT.Light.Logger.LoggerLevels.INFO,arguments)},warn:function(a){this._reportToLog(EBGVT.Light.Logger.LoggerLevels.WARN,arguments)},error:function(a){this._reportToLog(EBGVT.Light.Logger.LoggerLevels.ERROR,arguments)},exception:function(a,b){var c="string"!==b?this._format("Exception in {0}. message: {1}",
a,b.message):this._format("Exception in: {0}. message: {1}",a,b);b.stack&&(c+=this._format(" stack: {0}",b.stack));this._reportToLog(EBGVT.Light.Logger.LoggerLevels.ERROR,[c])},startGroup:function(a){this._supportNesting()&&this.startNestingGroupNames.push(a)},endGroup:function(){this._supportNesting()&&0<this.endNestingGroupNames.length&&window.console.groupEnd(this.endNestingGroupNames.pop())},_consoleAvailable:function(){try{return void 0!==window&&void 0!==window.console}catch(a){return!1}},_supportNesting:function(){return this._consoleAvailable()?
void 0!==window.console.group:!1},_supportErrorMessage:function(){return void 0!==window.console.error},_supportInfoMessage:function(){return void 0!==window.console.info||void 0!==window.opera},_supportWarnMessage:function(){return void 0!==window.console.warn||void 0!==window.opera},_supportObjectView:function(){return void 0!==window.console.dir||void 0!==window.opera},_callConsoleFunction:function(a,b){var c=!1;switch(a){case EBGVT.Light.Logger.LoggerLevels.INFO:this._supportInfoMessage()&&(window.console.info(b),
c=!0);break;case EBGVT.Light.Logger.LoggerLevels.WARN:this._supportWarnMessage()&&(window.console.warn(b),c=!0);break;case EBGVT.Light.Logger.LoggerLevels.ERROR:this._supportErrorMessage()&&(consoleFunction=window.console.error(b),c=!0)}c||window.console.log(b)},_format:function(a){for(var b=1;b<arguments.length;b++)a=a.replace(RegExp("\\{"+(b-1)+"\\}","gi"),""+arguments[b]);return a},_getTimestamp:function(){if(this.timestamp)return EBGVT.Light.Infra.getTimestamp()},_reportToLog:function(a,b){if(this._level>=
a&&this._consoleAvailable()){var c=b[0];"[object String]"!==Object.prototype.toString.call(c)?this._supportObjectView()||(c=c.toString()):c=this._format.apply(null,b);this.timestamp&&"[object String]"===Object.prototype.toString.call(c)&&(c=this._getTimestamp()+": "+c);if(void 0===window.opera){for(;this.startNestingGroupNames.length;)window.console.group(this.startNestingGroupNames[0]),this.endNestingGroupNames.push(this.startNestingGroupNames.shift());this._callConsoleFunction(a,c)}else opera.postError(c)}}};
EBGVT.ServerCommunicator=function(a){this.logger=a;this._browserDetector=new EBGVT.BrowserDetector;this._urlReportTimeout=100;this._imgArr=[];for(i=0;10>i;i++)this._imgArr.push(new Image)};
EBGVT.ServerCommunicator.prototype={raiseServerCall:function(a,b,c){this._scriptTag(a,b,c)},reportUrlsList:function(a){for(var b=0;b<this._imgArr.length;b++)this.reportUrl(a,this._imgArr[b])},reportUrl:function(a,b){if(0<a.length){var c=this,d=a.shift();b.onload=b.onerror=function(){c.reportUrl(a,b)};b.src=d;this.logger&&this.logger.info("Reporting URL "+d)}},_scriptTag:function(a,b,c){if(c)document.write("<script src='"+a+"'><\/script>");else{var d=document.createElement("script");d.type="text/"+
(a.type||"javascript");d.src=a.src||a;d.async=!0;d.onreadystatechange=d.onload=function(){var a=d.readyState;if(b&&!b.done&&(!a||/loaded|complete/.test(a)))b.done=!0,b(bsResponse)};this.logger&&this.logger.info("Scripted server call: "+a);EBGVT.Light.Infra.addChildToPage(d)}}};EBGVT.OneTagEnum=function(){};
EBGVT.OneTagEnum.UrlParamNames={ID:"onetagid",DISP_TYPE:"dispType",SYNC:"sync",ONETAG_URL:"ebOneTagURL",PAGE_URL:"pageurl",DEBUG_MODE:"debugmode",NO_SCRIPT:"ns",MOBILE:"mb",ACTIVITY_PARAMS:"activityValues",RETARGET_PARAMS:"retargetingValues",DYNAMIC_RETARGET_PARAMS:"dynamicRetargetingValues",CONDITIONAL_PARAMS:"acp",RANDOM:"rnd",SEC_CALL:"secCall",SESSION_ID:"sessionid",AD_TRUTH_USER_ID:"ATData",CACHED_USER_ID:"cuid",DEVICE9_USER_ID:"d9id",ORIG_URL_LENGTH:"origLength",SERVING_PIPE:"/Serving",PREV_SERVING_PIPE:"/BurstingPipe",
BROWSER_EVENT:"tp_be"};EBGVT.OneTagEnum.DisplayTypes={IFRAME:"iframe",JAVASCRIPT:"js"};EBGVT.OneTagEnum.HttpProtocol={HTTP:"http",HTTPS:"https"};EBGVT.OneTagEnum.PreServingTasks={AD_TRUTH:1,CACHED_USER_ID:2,DEVICE9_USER_ID:3};EBGVT.RuleManager=function(a,b){if(EBGVT.Light.Infra.isDefined(a))this._sessionId=b,this._buildRulesArray(a)};
EBGVT.RuleManager.prototype={_rules:[],_rulesHitted:[],_buildRulesArray:function(a){for(var b in a)this._rules.push(new EBGVT.Rule(a[b],{binding:this,func:this._onRuleHit}))},_onRuleHit:function(a){if(versaTagObj){-1==EBGVT.Light.Infra.indexOfArray(this._rulesHitted,a)&&this._rulesHitted.push(a);this._timeoutHandler&&clearTimeout(this._timeoutHandler);var b=this;this._timeoutHandler=setTimeout(function(){versaTagObj.generateRequest(null,{sessionId:b._sessionId,browserEvent:b._rulesHitted},!0);b._rulesHitted=
[]},1)}}};EBGVT.Events=EBGVT.Events||{};EBGVT.Rule=function(a,b){this._id=a.id;this._callback=b;this._createEvents(a);this._conditions=a.conditions||this._getDefaultConditionString()};
EBGVT.Rule.prototype={_createEvents:function(a){this._events={};var b=/e[0-9]/i,c;for(c in a)if(a.hasOwnProperty(c)&&b.test(c))try{EBGVT.Events[a[c].type]&&(this._events[c]=new EBGVT.Events[a[c].type](c,a[c].data,{func:this._eventMatchHandler,binding:this}))}catch(d){}},_getDefaultConditionString:function(){var a="",b=[],c;for(c in this._events)b.push(c);if(1==b.length)return b[0];try{a+=b[0];a+=b[1];a+="|";for(c=2;c<b.length;c++)a+=b[c]+"|"}catch(d){}return a},_eventMatchHandler:function(){this._checkRuleHit(this._conditions)&&
(this._resetEventStatus(),this._callback.func.apply(this._callback.binding,[this._id]))},_resetEventStatus:function(){for(var a in this._events)this._events[a].reset()},_checkRuleHit:function(a){try{var b=this._breakConditionString(a);if(1==b.length)return this._evaluateEvent(b[0]);var c=b[0],d=b[1],e=0,e="&"==b[2]?this._evaluateEvent(c)&&this._evaluateEvent(d)?1:0:this._evaluateEvent(c)||this._evaluateEvent(d)?1:0;return this._checkRuleHit(e+a.substring(b.join("").length))}catch(f){return!1}},_evaluateEvent:function(a){if(!isNaN(a))return!!(1*
a);a=this._events[a];return 1*(a&&a.applied)},_breakConditionString:function(a){for(var b=[],c=0;c<a.length;c++){var d=a.charAt(c);if(isNaN(d))if("e"==d)b.push("e"+a.charAt(++c));else{if("&"==d||"|"==d){b.push(d);break}}else b.push(d)}return b}};EBGVT.Events.ElementEvent=function(a,b,c){(EBGVT.Light.Infra.isDefined(b)||EBGVT.Light.Infra.isDefined(c))&&this.init(a,b,c)};
EBGVT.Events.ElementEvent.prototype={applied:!1,init:function(a,b,c){var d=this;this._wins=this._getWindowsArray();var e=this._select(decodeURIComponent(b.selector));if("loading"==document.readyState||!e.length)setTimeout(function(){d.init(a,b,c)},100);else{this._id=a;this._callback=c;for(var f=0;f<e.length;f++)EBGVT.Light.Infra.addEventListener(e[f],b.eventName,function(a){d.onEvent(a)})}},onEvent:function(){this.applied=!0;this._callback.func.apply(this._callback.binding,[this._id])},_select:function(a){for(var b=
[],c=0;c<this._wins.length;c++){var d=this._wins[c].document.querySelectorAll(a);if(d)for(var e=0;e<d.length;e++)b.push(d[e])}return b},_getWindowsArray:function(){for(var a=window,b=[a];a.self!==a.parent;)try{if(a.parent.document.domain)a=a.parent,b.push(a);else return b}catch(c){break}return b},reset:function(){this.applied=!1}};function p(a){return function(){return a}}
(function(){function a(a){try{if(navigator.plugins&&navigator.plugins.length)for(var b=0;b<navigator.plugins.length;b++){var c=navigator.plugins[b];if(0<=c.name.indexOf(a))return c.name+(c.description?"|"+c.description:"")}}catch(d){}return""}function b(b){var u=new Date,y=new Date,g=[p("TF1"),p("015"),function(){return ScriptEngineMajorVersion()},function(){return ScriptEngineMinorVersion()},function(){return ScriptEngineBuildVersion()},function(){return h("{7790769C-0471-11D2-AF11-00C04FA35D02}")},
function(){return h("{89820200-ECBD-11CF-8B85-00AA005B4340}")},function(){return h("{283807B5-2C60-11D0-A31D-00AA00B92C03}")},function(){return h("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return h("{44BBA848-CC51-11CF-AAFA-00AA00B6015C}")},function(){return h("{9381D8F2-0288-11D0-9501-00AA00B911A5}")},function(){return h("{4F216970-C90C-11D1-B5C7-0000F8051515}")},function(){return h("{5A8D6EE0-3E18-11D0-821E-444553540000}")},function(){return h("{89820200-ECBD-11CF-8B85-00AA005B4383}")},
function(){return h("{08B0E5C0-4FCB-11CF-AAA5-00401C608555}")},function(){return h("{45EA75A0-A269-11D1-B5BF-0000F8051515}")},function(){return h("{DE5AED00-A4BF-11D1-9948-00C04F98BBC9}")},function(){return h("{22D6F312-B0F6-11D0-94AB-0080C74C7E95}")},function(){return h("{44BBA842-CC51-11CF-AAFA-00AA00B6015B}")},function(){return h("{3AF36230-A269-11D1-B5BF-0000F8051515}")},function(){return h("{44BBA840-CC51-11CF-AAFA-00AA00B6015C}")},function(){return h("{CC2A9BA0-3BDD-11D0-821E-444553540000}")},
function(){return h("{08B0E5C0-4FCB-11CF-AAA5-00401C608500}")},function(){return eval("navigator.appCodeName")},function(){return eval("navigator.appName")},function(){return eval("navigator.appVersion")},function(){return f(["navigator.productSub","navigator.appMinorVersion"])},function(){return eval("navigator.browserLanguage")},function(){return eval("navigator.cookieEnabled")},function(){return f(["navigator.oscpu","navigator.cpuClass"])},function(){return eval("navigator.onLine")},function(){return eval("navigator.platform")},
function(){return eval("navigator.systemLanguage")},function(){return eval("navigator.userAgent")},function(){return f(["navigator.language","navigator.userLanguage"])},function(){return eval("document.defaultCharset")},function(){return eval("document.domain")},function(){return eval("screen.deviceXDPI")},function(){return eval("screen.deviceYDPI")},function(){return eval("screen.fontSmoothingEnabled")},function(){return eval("screen.updateInterval")},function(){return 0!==Math.abs(s-t)},function(){return d(u)},
p("@UTC@"),function(){var a=0,a=0;d(u)&&(a=Math.abs(s-t));return-(u.getTimezoneOffset()+a)/60},function(){return(new Date(2005,5,7,21,33,44,888)).toLocaleString()},function(){return eval("screen.width")},function(){return eval("screen.height")},function(){return o.Acrobat},function(){return o.Flash},function(){return o.QuickTime},function(){return o["Java Plug-in"]},function(){return o.Director},function(){return o.Office},p("@CT@"),function(){return s},function(){return t},function(){return u.toLocaleString()},
function(){return eval("screen.colorDepth")},function(){return eval("window.screen.availWidth")},function(){return eval("window.screen.availHeight")},function(){return eval("window.screen.availLeft")},function(){return eval("window.screen.availTop")},function(){return a("Acrobat")},function(){return a("Adobe SVG")},function(){return a("Authorware")},function(){return a("Citrix ICA")},function(){return a("Director")},function(){return a("Flash")},function(){return a("MapGuide")},function(){return a("MetaStream")},
function(){return a("PDFViewer")},function(){return a("QuickTime")},function(){return a("RealOne")},function(){return a("RealPlayer Enterprise")},function(){return a("RealPlayer Plugin")},function(){return a("Seagate Software Report")},function(){return a("Silverlight")},function(){return a("Windows Media")},function(){return a("iPIX")},function(){return a("nppdf.so")},function(){var a=document.createElement("span");a.innerHTML="&nbsp;";a.style.position="absolute";a.style.left="-9999px";document.body.appendChild(a);
var b=a.offsetHeight;document.body.removeChild(a);return b}];e();for(var l="",v=0;v<g.length;v++){b&&(l+=c(g[v].toString(),'"',"'",!0),l+="=");var w;try{w=g[v](this)}catch(j){w=""}l+=b?w:escape(w);l+=";";b&&(l+="\\n")}l=c(l,escape("@UTC@"),(new Date).getTime());l=c(l,escape("@CT@"),(new Date).getTime()-y.getTime());return window.f1b5?window.f1b5(l):l}function c(a,b,c,d){"boolean"!==typeof d&&(d=!1);for(var e=!0,f;0<=(f=a.indexOf(b))&&(d||e);)a=a.substr(0,f)+c+a.substr(f+b.length),e=!1;return a}function d(a){var b=
Math.min(s,t);return 0!==Math.abs(s-t)&&a.getTimezoneOffset()===b}function e(){for(var a="Acrobat,Flash,QuickTime,Java Plug-in,Director,Office".split(","),b=0;b<a.length;b++){var c=a[b],d=o,e=c,f=c,c="";try{if(navigator.plugins&&navigator.plugins.length)for(var g=RegExp(f+".* ([0-9._]+)"),f=0;f<navigator.plugins.length;f++){var h=g.exec(navigator.plugins[f].name);null===h&&(h=g.exec(navigator.plugins[f].description));h&&(c=h[1])}else if(window.ActiveXObject&&m[f])try{var j=new ActiveXObject(m[f][0]),
c=m[f][1](j)}catch(k){c=""}}catch(n){c=n.message}d[e]=c}}function f(a){for(var b=0;b<a.length;b++)try{var c=eval(a[b]);if(c)return c}catch(d){}return""}function h(a){var b="";try{"undefined"!==typeof k.a.getComponentVersion&&(b=k.a.getComponentVersion(a,"ComponentID"))}catch(c){a=c.message.length,b=escape(c.message.substr(0,40<a?40:a))}return b}function x(a){function b(a){d=d<<a[0]|a[1];for(e+=a[0];6<=e;)a=d>>e-6&63,c+=j.substring(a,a+1),e-=6,d^=a<<e}var c="",d=0,e=0;b([6,(a.length&7)<<3|0]);b([6,
a.length&56|1]);for(var f=0;f<a.length;f++){if(void 0==q[a.charCodeAt(f)])return;b(q[a.charCodeAt(f)])}b(q[0]);0<e&&b([6-e,0]);return c}var k={},s=(new Date(2005,0,15)).getTimezoneOffset(),t=(new Date(2005,6,15)).getTimezoneOffset(),o=[],m={Flash:["ShockwaveFlash.ShockwaveFlash",function(a){return a.getVariable("$version")}],Director:["SWCtl.SWCtl",function(a){return a.ShockwaveVersion("")}]};try{k.a=document.createElement("span"),"undefined"!==typeof k.a.addBehavior&&k.a.addBehavior("#default#clientCaps")}catch(n){}var o=
{},q={1:[4,15],110:[8,239],74:[8,238],57:[7,118],56:[7,117],71:[8,233],25:[8,232],101:[5,28],104:[7,111],4:[7,110],105:[6,54],5:[7,107],109:[7,106],103:[9,423],82:[9,422],26:[8,210],6:[7,104],46:[6,51],97:[6,50],111:[6,49],7:[7,97],45:[7,96],59:[5,23],15:[7,91],11:[8,181],72:[8,180],27:[8,179],28:[8,178],16:[7,88],88:[10,703],113:[11,1405],89:[12,2809],107:[13,5617],90:[14,11233],42:[15,22465],64:[16,44929],"0":[16,44928],81:[9,350],29:[8,174],118:[8,173],30:[8,172],98:[8,171],12:[8,170],99:[7,84],
117:[6,41],112:[6,40],102:[9,319],68:[9,318],31:[8,158],100:[7,78],84:[6,38],55:[6,37],17:[7,73],8:[7,72],9:[7,71],77:[7,70],18:[7,69],65:[7,68],48:[6,33],116:[6,32],10:[7,63],121:[8,125],78:[8,124],80:[7,61],69:[7,60],119:[7,59],13:[8,117],79:[8,116],19:[7,57],67:[7,56],114:[6,27],83:[6,26],115:[6,25],14:[6,24],122:[8,95],95:[8,94],76:[7,46],24:[7,45],37:[7,44],50:[5,10],51:[5,9],108:[6,17],22:[7,33],120:[8,65],66:[8,64],21:[7,31],106:[7,30],47:[6,14],53:[5,6],49:[5,5],86:[8,39],85:[8,38],23:[7,
18],75:[7,17],20:[7,16],2:[5,3],73:[8,23],43:[9,45],87:[9,44],70:[7,10],3:[6,4],52:[5,1],54:[5,0]},r="%20,;;;,%3B,%2C,und,fin,ed;,%28,%29,%3A,/53,ike,Web,0;,.0,e;,on,il,ck,01,in,Mo,fa,00,32,la,.1,ri,it,%u,le".split(","),j=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz";window.f1b5=function(a){for(var b=a,c=0;r[c];c++)b=b.split(r[c]).join(String.fromCharCode(c+1));b=x(b);if(void 0==b)return a;for(var c=65535,d=0;d<a.length;d++)c=(c>>>8|c<<8)&65535,c^=a.charCodeAt(d)&255,c^=(c&255)>>
4,c^=c<<12&65535,c^=(c&255)<<5&65535;c&=65535;a=""+j.charAt(c>>>12);a+=j.charAt(c>>>6&63);a+=j.charAt(c&63);return b+a};k.collect=function(a){try{if(!a)return b();var c;a:{var d;try{d=document.getElementById(a)}catch(e){}if(null===d||"undefined"===typeof d)try{d=document.getElementsByName(a)[0]}catch(f){}if(null===d||"undefined"===typeof d)for(var g=0;g<document.forms.length;g++)for(var h=document.forms[g],j=0;j<h.elements.length;j++){var k=h[j];if(k.name===a||k.id===a){c=k;break a}}c=d}if(null!==
c)try{c.value=b()}catch(m){c.value=escape(m.message)}}catch(n){}};window.fortyone=k;var g=navigator.userAgent.toLowerCase();"Gecko"===navigator.product&&2>=parseInt(g.substring(g.indexOf("rv:")+3,g.indexOf(")",g.indexOf("rv:")+3)).split(".")[0])&&window.fortyone.collect()})();EBUidCacheClass=function(){};
EBUidCacheClass.prototype={getUserId:function(a){var b=null;return b=window.ebUserIdGuid?window.ebUserIdGuid:EBUidCache._handleCacheUserIdentification(a)},_handleCacheUserIdentification:function(a){var b=null;return b=this._getDataFromRemoteServer(this._buildURL(a),this._handleServerResponse,this,!1)},_handleServerResponse:function(a,b){if(!b&&typeof(void 0!=a))try{return(new Function(a))(),gEBMainWindow.ebUserIdGuid}catch(c){}return null},_buildURL:function(a){return this._getRequestProtocol(a)+
a.bs+"/Serving?EBUI.js&cn=cu"},_getRequestProtocol:function(a){if(a.ebPtcl)return a.ebPtcl;var a="https://",b=location.protocol;if("javascript:"==b)try{b=parent.location.protocol}catch(c){}"http:"==b&&(a=b+"//");return a},_getDataFromRemoteServer:function(a,b,c,d,e){d=void 0!=typeof d?d:!0;e=void 0!=typeof e?e:!1;try{if(this._isXMLHttpRequestSupported()){var f=new XMLHttpRequest;f.open("GET",a,d);f.send();return!d?b.call(c,e?f.responseXML:f.responseText):null}}catch(h){return null}},_isXMLHttpRequestSupported:function(){var a=
window.XMLHttpRequest?new XMLHttpRequest:null;return a&&"boolean"==typeof a.withCredentials}};EBUidCache=new EBUidCacheClass;
Device9={insertCode2DOM:function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.appendChild(document.createTextNode(a));(document.body||document.head||document.documentElement).appendChild(b)},injectD9Code:function(a){(a=a.sid?a.sid:a.sessionId)&&Device9.insertCode2DOM("var D9v = {}; D9v.TAG = 1; D9v.CampID = '3112';D9v.UserID = ''; D9v.ImpID = '';D9v.ImpID = '"+a+"';var D9r = {};(function() { var D9scr = document.createElement('script');     D9scr.type = 'text/javascript'; D9scr.async = true;D9scr.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'tag.device9.com/d9core';var D9 = document.getElementsByTagName('script')[0]; D9.parentNode.insertBefore(D9scr, D9);})();")}};
EBGVT.UserIdProvider=function(){this._providers={};this.logNeeded=EBGVT.Light.Infra.getUrlParameter(EBGVT.Light.Logger.DebugMode)?1:0;this.oneTagLogger=new EBGVT.Light.Logger(EBGVT.Light.Infra.getUrlParameter(EBGVT.Light.Logger.DebugMode));this._registerProviders()};EBGVT.UserIdProvider.ResponseType={GET:0,POST:1};EBGVT.UserIdProvider.ProvidersEnum=["AdTruth","EBUidCache","Device9"];
EBGVT.UserIdProvider.prototype={_registerProviders:function(){this.registerProvider("AdTruth",EBGVT.OneTagEnum.UrlParamNames.AD_TRUTH_USER_ID,"fortyone.collect",!0,!1);this.registerProvider("EBUidCache",EBGVT.OneTagEnum.UrlParamNames.CACHED_USER_ID,"EBUidCache.getUserId",!0,!0);this.registerProvider("Device9",EBGVT.OneTagEnum.UrlParamNames.DEVICE9_USER_ID,"Device9.injectD9Code",!0,!0)},registerProvider:function(a,b,c,d,e){if(this._providers[a])this.oneTagLogger.warn(a+" provider already exist, provider not registered!");
else{var f=this._verifyProviderCallbackFunc(c);f?(this.oneTagLogger.info("Registering "+a+" provider"),this._providers[a]={tokenName:b,funcName:c,func:f,id:null,shouldCache:d,sendData:e}):this.oneTagLogger.info("Could not resolve "+a+" handler function name")}},_generateUserIds:function(a,b){for(var c=0;c<a.length;c++){var d=a[c],e=this._providers[d],f=null;if(e)if(!e.id||!e.shouldCache){this.oneTagLogger.info("calculating ID with "+d);try{f=e.sendData?e.func.apply(null,[b]):e.func.apply()}catch(h){f=
null,this.oneTagLogger.error("Got exception during "+d+" ID calculation: "+h)}e.id=f}else this.oneTagLogger.info("Using "+d+" cached ID")}},getUserIds:function(a,b,c){var d="",a=this._getValidProviderNames(a);this._generateUserIds(a,c);return d=this._formatResponse(a,b)},_formatResponse:function(a,b){var c="";switch(b){default:case EBGVT.UserIdProvider.ResponseType.GET:for(var d=0;d<a.length;d++){var e=this._providers[a[d]];e.id&&(c+="&"+e.tokenName+"="+e.id)}case EBGVT.UserIdProvider.ResponseType.POST:}return c},
_verifyProviderCallbackFunc:function(a){for(var b=a.split("."),c=null,d=window,e=0,f=b.length;e<f;e++){var h=b[e];if(void 0!==d[h]&&(d=d[h],e==f-1&&"function"==typeof d)){this.oneTagLogger.debug("Resolved function "+a);c=d;break}}return c},_getValidProviderNames:function(a){var b=[];if("array"==EBGVT.Light.Infra.typeOf(a))for(var c=0;c<a.length;c++)if("number"==EBGVT.Light.Infra.typeOf(a[c])){var d=EBGVT.UserIdProvider.ProvidersEnum[a[c]-1];d&&(b[b.length]=d)}else this.oneTagLogger.error("error in _getValidProviderNames in UserIdentification.js - uip should include only numbers");
return b}};EBGVT.OneTagLogger=function(){};EBGVT.OneTag=function(){this.logNeeded=EBGVT.Light.Infra.getUrlParameter(EBGVT.Light.Logger.DebugMode)?1:0;this.oneTagLogger=new EBGVT.Light.Logger(EBGVT.Light.Infra.getUrlParameter(EBGVT.Light.Logger.DebugMode));this.oneTagLogger.timestamp=!0;this.serverCommunicator=this.serverCommunicator||new EBGVT.ServerCommunicator(this.oneTagLogger);this._oneTagObj=this.pageUrl=null;if(EBGVT.Light.Infra.isDefined(window.versaTag))this._oneTagObj=versaTag};
EBGVT.OneTag.prototype={generateRequest:function(a,b,c){if(this._oneTagObj){this.oneTagLogger.info("One Tag Started");this.pageUrl=a;if(b&&b.firstPartyServingDomain)this._oneTagObj.bsUrl=b.firstPartyServingDomain+EBGVT.OneTagEnum.UrlParamNames.SERVING_PIPE;var a=b&&b.sessionId?b.sessionId:"0",d=b&&b.browserEvent?"$$"+b.browserEvent.join("&")+"$$":"",c=this._generateBsURL(this._oneTagObj,this.pageUrl,c,a,d);this.oneTagLogger.info("Server URL: "+c);if(b&&b.preServingTasks)b.bs=this._oneTagObj.bsUrl.substr(0,
this._oneTagObj.bsUrl.indexOf("/")),c=this._handlePreServingTasks(b.preServingTasks,c,b);if(this._oneTagObj.dispType.toLowerCase()==EBGVT.OneTagEnum.DisplayTypes.IFRAME)EBGVT.Light.Infra.createUnfriendlyIframe(c,this._oneTagObj.sync);else{var e=this;this.serverCommunicator.raiseServerCall(c,function(a){e._handleResponse(a)},1==this._oneTagObj.sync)}}else if(b&&c){c=document.location.href;b.bs=document.domain;if(b&&b.firstPartyServingDomain)a=document.domain,d=a+location.pathname,a&&0<a.length&&(c=
0<c.indexOf(d)?c.replace(d,b.firstPartyServingDomain+EBGVT.OneTagEnum.UrlParamNames.SERVING_PIPE):c.replace(a,b.firstPartyServingDomain));c=c.replace(EBGVT.OneTagEnum.UrlParamNames.DISP_TYPE+"="+EBGVT.OneTagEnum.DisplayTypes.IFRAME,EBGVT.OneTagEnum.UrlParamNames.DISP_TYPE+"="+EBGVT.OneTagEnum.DisplayTypes.JAVASCRIPT);c=c.replace("cn=ot","cn=ot&"+EBGVT.OneTagEnum.UrlParamNames.SEC_CALL+"=1"+(b.sessionId?"&sessionid="+b.sessionId:""));c=this._handlePreServingTasks(b.preServingTasks,c,b);b=c.substr(c.indexOf(EBGVT.OneTagEnum.UrlParamNames.SYNC)+
(EBGVT.OneTagEnum.UrlParamNames.SYNC+"=").length,1);e=this;this.serverCommunicator.raiseServerCall(c,function(a){e._handleResponse(a)},1==b)}},setActivityParam:function(a,b){if(!this._oneTagObj.activityParams)this._oneTagObj.activityParams={};this._oneTagObj.activityParams[a]=b},getActivityParam:function(a){var b=null;this._oneTagObj.activityParams&&this._oneTagObj.activityParams[a]&&(b=this._oneTagObj.activityParams[a]);return b},clearActivityParam:function(){this._oneTagObj.activityParams={}},setRetargetParam:function(a,
b){if(!this._oneTagObj.retargetParams)this._oneTagObj.retargetParams={};this._oneTagObj.retargetParams[a]=b},getRetargetParam:function(a){var b=null;this._oneTagObj.retargetParams&&this._oneTagObj.retargetParams[a]&&(b=this._oneTagObj.retargetParams[a]);return b},clearRetargetParam:function(){this._oneTagObj.retargetParams={}},setDynamicRetargetParam:function(a,b){if(!this._oneTagObj.dynamicRetargetParams)this._oneTagObj.dynamicRetargetParams={};this._oneTagObj.dynamicRetargetParams[a]=b},getDynamicRetargetParam:function(a){var b=
null;this._oneTagObj.dynamicRetargetParams&&this._oneTagObj.dynamicRetargetParams[a]&&(b=this._oneTagObj.dynamicRetargetParams[a]);return b},clearDynamicRetargetParam:function(){this._oneTagObj.dynamicRetargetParams={}},setConditionalParam:function(a,b){if(!this._oneTagObj.conditionalParams)this._oneTagObj.conditionalParams={};this._oneTagObj.conditionalParams[a]=b},getConditionalParam:function(a){var b=null;this._oneTagObj.conditionalParams&&this._oneTagObj.conditionalParams[a]&&(b=this._oneTagObj.conditionalParams[a]);
return b},clearConditionalParam:function(){this._oneTagObj.conditionalParams={}},_generateBsURL:function(a,b,c,d,e){a.bsUrl=a.bsUrl.replace(EBGVT.OneTagEnum.UrlParamNames.PREV_SERVING_PIPE,EBGVT.OneTagEnum.UrlParamNames.SERVING_PIPE);var f=this._getProtocol(a.ptcl)+a.bsUrl+"?cn=ot&"+EBGVT.OneTagEnum.UrlParamNames.ID+"="+a.id+"&"+EBGVT.OneTagEnum.UrlParamNames.DISP_TYPE+"="+a.dispType+"&"+EBGVT.OneTagEnum.UrlParamNames.SYNC+"="+a.sync;c&&(f+="&"+EBGVT.OneTagEnum.UrlParamNames.SEC_CALL+"=1");"0"!=d&&
(f+="&"+EBGVT.OneTagEnum.UrlParamNames.SESSION_ID+"="+d);a.mobile&&(f+="&"+EBGVT.OneTagEnum.UrlParamNames.MOBILE+"="+a.mobile);e&&(f+="&"+EBGVT.OneTagEnum.UrlParamNames.BROWSER_EVENT+"="+e);b=b?escape(b):escape(EBGVT.Light.Infra.getWindowLocation());f+="&"+EBGVT.OneTagEnum.UrlParamNames.PAGE_URL+"=$$"+b+"$$";f+=this._prepareParamUrl(a.activityParams,EBGVT.OneTagEnum.UrlParamNames.ACTIVITY_PARAMS);f+=this._prepareParamUrl(a.retargetParams,EBGVT.OneTagEnum.UrlParamNames.RETARGET_PARAMS);f+=this._prepareParamUrl(a.conditionalParams,
EBGVT.OneTagEnum.UrlParamNames.CONDITIONAL_PARAMS);f+=this._prepareParamUrl(a.dynamicRetargetParams,EBGVT.OneTagEnum.UrlParamNames.DYNAMIC_RETARGET_PARAMS);a.dispType.toLowerCase()==EBGVT.OneTagEnum.DisplayTypes.IFRAME&&(f+="&"+EBGVT.OneTagEnum.UrlParamNames.ONETAG_URL+"="+escape(document.getElementById("ebOneTagUrlId").src));this.logNeeded&&(f+="&"+EBGVT.Light.Logger.DebugMode+"="+this.logNeeded);f+="&"+EBGVT.OneTagEnum.UrlParamNames.NO_SCRIPT+"=0";f+="&"+EBGVT.OneTagEnum.UrlParamNames.RANDOM+"="+
EBGVT.Light.Infra.getRandomNumber();a.debugData&&(f+="&"+a.debugData);if(a=EBGVT.Light.Infra.getTopLevelReferrer(window))b=EBGVT.Light.Infra.getTokenValueFromURL("ebReferrer",a),(c=EBGVT.Light.Infra.getTokenValueFromURL("usercookie",a))&&(f+="&usercookie=u2="+c),a=b?b:a,b=EBGVT.Light.Infra.urlAvailableLength(f)-48,0<b&&(a.length>b&&(a=a.substr(0,b)),f+="&referrer=$$"+a+"$$");return f},_prepareParamUrl:function(a,b){var c=!0,d="",e;for(e in a)if(a.hasOwnProperty(e)&&(null!=a[e]&&b!=EBGVT.OneTagEnum.UrlParamNames.CONDITIONAL_PARAMS&&
""!=a[e]||b==EBGVT.OneTagEnum.UrlParamNames.CONDITIONAL_PARAMS))c?(d+="&"+b+"=$$"+e+"="+a[e],c=!1):d+="&"+e+"="+a[e];c||(d+="$$");return d},_getProtocol:function(a){var b="http://";return b=a&&a.toLowerCase()==EBGVT.OneTagEnum.HttpProtocol.HTTP?"http://":a&&a.toLowerCase()==EBGVT.OneTagEnum.HttpProtocol.HTTPS?"https://":"https:"==EBGVT.Light.Infra.getWindowLocation().protocol?"https://":"http://"},_handleResponse:function(a){this.oneTagLogger.info("Server response: "+a);if(a=this._deserializeResponse(a))a.preServingTasks||
a.firstPartyServingDomain?this.generateRequest(this.pageUrl,a,!0):(this._handleScriptTags(a.scripts),this._handleUrlTags(a.urls),this._handleCustomScript(a.customScript),this._handleServerMessages(a.logMessages),this._handleClientRules(a.clientRules,a.sessionId))},_handleClientRules:function(a,b){this.ruleManager=new EBGVT.RuleManager(a,b)},_handlePreServingTasks:function(a,b,c){return"undefined"==typeof a?b:b=this._addProviderUserId(a,b,c)},_deserializeResponse:function(a){var b;try{this.logNeeded&&
-1!=a.indexOf("/*")&&(a=a.substring(0,a.lastIndexOf("/*"))),b=EBGVT.JSON.parse(unescape(a))}catch(c){this.oneTagLogger.exception("OneTag._deserializeResponse",c)}return b},_handleCustomScript:function(a){if(a&&("http:"==a.substring(0,5).toLowerCase()||"https:"==a.substring(0,6).toLowerCase())){var b=document.createElement("script");b.type="text/javascript";b.src=a;EBGVT.Light.Infra.addScriptElement(b)}},_handleServerMessages:function(a){if(a&&0<a.length){this.oneTagLogger.timestamp=!1;this.oneTagLogger.info("Server Messages:");
for(var b=0;b<a.length;b++)a[b]&&this.oneTagLogger.info("  "+a[b]);this.oneTagLogger.timestamp=!0}},_handleScriptTags:function(a){if(a)for(var b=0;b<a.length;b++)a[b]&&this._injectScripts(a[b])},_handleUrlTags:function(a){a&&this.serverCommunicator.reportUrlsList(a)},_injectScripts:function(a){if(a){a="<html><head></head><body>"+a+"</body></html>";this.oneTagLogger.info("Script Injection: "+a);var b=EBGVT.Light.Infra.createFriendlyIframe();EBGVT.Light.Infra.addChildToPage(b);document.documentMode&&
7<document.documentMode&&!EBGVT.Light.Infra.isIframeScriptable(b)&&EBGVT.Light.Infra.enableIframeScriptable(b);EBGVT.Light.Infra.writeToFriendlyIframe(b,a,!0)}},_addProviderUserId:function(a,b,c){for(var d=new EBGVT.UserIdProvider,e=0;e<a.length;e++){var f=d.getUserIds([a[e]],EBGVT.UserIdProvider.ResponseType.GET,c);if(EBGVT.Light.Infra.urlAvailableLength(b)-48>f.length)b+=f;else{b+="&"+EBGVT.OneTagEnum.UrlParamNames.ORIG_URL_LENGTH+"="+(b.length+f.length+2);break}}return b}};var versaTagObj=new EBGVT.OneTag;
versaTagObj.generateRequest();
