try{var topdomain=top.document.domain;if(top!=self&&topdomain!=self.document.domain){top.location=self.location;}}catch(e){top.location=self.location;}var Display="";
var _use_URL=true;var _dont_use_URL=false;var news_type="";var _other_pages="Others";var _Concat_char="_";var _URL=document.URL;function create_coremetrics_tag(){return;
}function make_trackable(trackcontent){return;}function MyBrowser(){var agent=navigator.userAgent.toLowerCase();this.major=parseInt(navigator.appVersion);
this.minor=parseFloat(navigator.appVersion);this.ns=((agent.indexOf("mozilla")!=-1)&&((agent.indexOf("spoofer")==-1)&&(agent.indexOf("compatible")==-1)));
this.ns2=(this.ns&&(this.major==2));this.ns3=(this.ns&&(this.major==3));this.ns4b=(this.ns&&(this.minor<4.04));this.ns4=(this.ns&&(this.major>=4));this.ie=(agent.indexOf("msie")!=-1);
this.ie3=(this.ie&&(this.major==2));this.ie4=(this.ie&&(this.major>=4));this.dhtml=(this.major>=4);}var browser=new MyBrowser();if(!Array.prototype.push){function push(){for(var i=0;
i<arguments.length;i++){this[this.length]=arguments[i];}return this.length;}Array.prototype.push=push;}function open_window(url,win_name,w,h,pos,show_once,days_not_shown,pop_under,resize){if(show_once){if(GetCookie(win_name)){return;
}var exp=null;if(days_not_shown){exp=new Date();exp.setTime(exp.getTime()+(days_not_shown*24*60*60*1000));}SetCookie(win_name,"1",exp,"/");}var margin=20;
var screen_w=window.screen.width;var screen_h=window.screen.height;var pos_x=0;var pos_y=0;switch(pos){case"TL":pos_x=0+margin;pos_y=0+margin;break;case"TR":pos_x=screen_w-(margin+w);
pos_y=0+margin;break;case"BR":pos_x=screen_w-(margin+w);pos_y=screen_h-(margin+h+40);break;case"BL":pos_x=0+margin;pos_y=screen_h-(margin+h+40);break;case"CC":pos_x=(screen_w-w)/2;
pos_y=(screen_h-h)/2;break;default:pos_x=screen_w-(margin+w);pos_y=screen_h-(margin+h);break;}var win_pos=(browser.ns4)?",screenX="+pos_x+",screenY="+pos_y:(browser.ie4)?",left="+pos_x+",top="+pos_y:"";
var window_feature="width="+w+",height="+h+win_pos;if(resize){window_feature+="resizable=yes";}var pop_win=window.open(url,win_name,window_feature);if(pop_under!=null&&pop_under==1){pop_win.blur();
window.focus();}}function getExpDate(days){var c_exp=new Date();c_exp.setTime(c_exp.getTime()+(days*24*60*60*1000));return c_exp;}function SetCookie(name,value,expires,path,domain,secure){document.cookie=name+"="+value+((expires)?";expires="+expires.toGMTString():"")+((path)?";path="+path:"")+((domain)?";domain="+domain:"")+((secure)?";secure":"");
}function GetCookie(c_name,not_escape){var arg=c_name+"=";var arg_len=arg.length;var c_len=document.cookie.length;var x=0;while(x<c_len){var y=x+arg_len;
if(document.cookie.substring(x,y)==arg){return extractOut(y,not_escape);}x=document.cookie.indexOf(" ",x)+1;if(x==0){break;}}return null;}function extractOut(start_str,not_escape){var end_str=document.cookie.indexOf(";",start_str);
if(end_str==-1){end_str=document.cookie.length;}if(not_escape==1){return document.cookie.substring(start_str,end_str);}else{return unescape(document.cookie.substring(start_str,end_str));
}}var sn="military.index";var pn="FD-OO";function get_dart_values(extracturl,type,sitename,pagename){if(type=="richmedia-page"||type=="richmedia-mib"){cat="richmedia";
}else{cat="nonrichmedia";}if(type=="PAGE"||type=="richmedia-page"){sn="military.index";pn="FD-OO";}else{path_list=get_template_path(document.URL).split("/");
if(extracturl){sn="military."+path_list[0].toLowerCase();}else{if(sitename!=""){sn="military."+sitename;}else{sn="military."+path_list[0].toLowerCase();
}}if(extracturl){pn=path_list[1];}else{pn=pagename;}}}function get_url_OID(url){if(has_url_CURL(url)){return(url.substring(url.lastIndexOf("/")).split(",")[2]);
}else{return null;}}function has_url_CURL(url){return((url.substring(url.lastIndexOf("/")).split(",")).length==4);}function remove_url_CURL(url){if(has_url_CURL(url)){return url.substring(0,url.lastIndexOf("/"));
}else{return((url.lastIndexOf("/")==(url.length-1))?url.substring(0,url.length-1):url);}}function remove_url_parameters(url){if(url.indexOf("?")<0){return url;
}else{return url.substring(0,url.indexOf("?"));}}function remove_url_domain(url){if(url.indexOf("://")>=0){url=url.substring(url.indexOf("://")+3);}if(url.indexOf("/")>=0){return url.substring(url.indexOf("/")+1);
}else{return"";}}function get_template_path(url){return remove_url_CURL(remove_url_domain(remove_url_parameters(url)));}function getDomain(full_url){if(full_url!=null&&full_url!=""&&full_url.length!=0){if(full_url.split("//").length>1){return full_url.split("//")[1].split("/")[0];
}return full_url.split("/")[0];}else{return null;}}function getValueByKey(key,str){if(str==null){str=document.URL;}if(str.indexOf(key)<0){return"";}var v=(str.substring(str.indexOf(key)).split("="))[1];
if(v.indexOf("#")>=0){v=v.substring(0,v.indexOf("#"));}return v.split("&")[0];}function checkInternal(url){if((getDomain(url)).indexOf("military.com")){return url;
}else{return"EXTERNAL";}}var rand=Math.round(1000000*(Math.random()));function selectimg(tp,sn,pn,k,s,a,r,st,z,l,h,w,t){if(tp=="richmedia"||tp=="y"){if(browser.ns){setimg(sn,pn,k,s,a,r,st,z,l,h,w,t);
}else{cat="y";}}else{setimg(sn,pn,k,s,a,r,st,z,l,h,w,t);}}function setimg(sn,pn,k,s,a,r,st,z,l,h,w,t){var myurl="http://ad.doubleclick.net/";var myarg=sn+"/"+pn+";kw="+k+";s="+s+";a="+a+";r="+r+";st="+st+";z="+z+";loc="+l+";sst="+s+st+";sz="+h+"x"+w+";tile="+t+";ord="+rand+"?";
document.write('<A href="'+myurl+"jump/"+myarg+'" target=_top>');document.write('<img src="'+myurl+"ad/"+myarg+'" width='+h+" height="+w+" border=0 align=absmiddle>");
document.write("</A>");}var today=new Date();var _s=new Array("0","","","","","UNKNWN","UNKNWN","NONE","",today.getFullYear(),"");var mychip=GetCookie("LoginInfo");
if(mychip!=null){_s=mychip.split("|");}else{if(GetCookie("LoginMemberID")!=null){_s[0]=GetCookie("LoginMemberID");_s[1]=GetCookie("LoginContactsID");_s[2]=GetCookie("LoginLoginName");
_s[3]=GetCookie("LoginFirstName");_s[4]=GetCookie("LoginLastName");_s[5]=GetCookie("LoginServiceCode");_s[6]=GetCookie("status");_s[7]=GetCookie("rank");
_s[8]=GetCookie("zipCode");_s[9]=GetCookie("age");_s[10]=GetCookie("LoginFreeEmail");}}var s=_s[5];var age=_s[9];var r=_s[7];var st=_s[6];var z=_s[8];var t=1;
var a="ag0";age=today.getFullYear()-age;_age=0;_age=(age<10)?0:(age<18)?1:(age<25)?2:(age<35)?3:(age<50)?4:(age<65)?5:(age<120)?6:0;a="ag"+_age;switch(s){case"ARMY":sr=1;
_sr="Army";break;case"NAVY":sr=2;_sr="Navy";break;case"AIRFRC":sr=3;_sr="Air Force";break;case"COASTG":sr=4;_sr="Coast Guard";break;case"MARINE":sr=5;_sr="Marine Corps";
break;case"DOD":sr=6;_sr="Department of Defense";break;case"GOVERN":sr=8;_sr="Other Government";break;default:sr=7;_sr="Other or No Service Affiliation";
}switch(st){case"A":st="ad";_st="Active Duty";break;case"V20PLU":st="rm";_st="Retired Military";break;case"V20MIN":st="rl";_st="Veteran/Prior Service";
break;case"ACTRES":st="ra";_st="Reservist (Active)";break;case"INTRES":st="ri";_st="Inactive Res/Guard";break;case"NATGRD":st="ng";_st="National Guard";
break;case"ACDMEM":st="nmas";_st="Service Academy";break;case"RESTRA":st="rotc";_st="ROTC";break;case"OTHMIL":st="omp";_st="Other Military Program";break;
case"CONJON":st="cj";_st="Considering Joining";break;case"F":st="f";_st="Other Family Member";break;case"ENTHUS":st="me";_st="Military Enthusiast";break;
case"MILOTH":st="0";_st="Other";break;case"GOVEMP":st="ge";_st="Government Employee";break;case"DEFCON":st="df";_st="Defense Contractor";break;case"SPOUSE":st="sp";
_st="Spouse";break;case"SPOVET":st="sp";_st="Spouse";break;default:st="0";_st="Other";}if(r!=null&&r!="NONE"){if(r.indexOf("AE")==0||r.indexOf("AY")==0||r.indexOf("NY")==0||r.indexOf("MS")==0||r.indexOf("CG")==0||r.indexOf("DD")==0){r=r.substr(2,4);
}if(r.indexOf("GS")==0){r=r.substr(0,2);}r=r.replace("-","").toLowerCase();}else{r="0";}var cname="SRCT";var c_domain=getDomain(document.URL);c_domain=(c_domain.split(".").length>=3?c_domain.substring(c_domain.indexOf(".")):c_domain);
var cactv="ACTV";var ses_hrs=24;function numPad(n,l){var t="00000000000000000000";var s=new String(n);var sl=s.length;if(sl==l){return s;}if(sl>l){return s.substring(0,l);
}if(sl<l){return t.substring(0,(l-sl))+s;}}function getTStamp(){var y=today.getUTCFullYear();var m=today.getUTCMonth()+1;var d=today.getUTCDate();var h=today.getUTCHours();
return y+"-"+numPad(m,2)+"-"+numPad(d,2)+"-"+numPad(h,2);}function getVSID(){var min=today.getUTCMinutes();var sec=today.getUTCSeconds();var msec=today.getUTCMilliseconds();
var tstamp=getTStamp();return tstamp+"-"+numPad(min,2)+"-"+numPad(sec,2)+"-"+numPad(msec,3)+"-"+numPad(rand,6);}function setVID(){var vid="";var c_val="";
if((c_val=GetCookie(cactv))&&(vid=getCV(c_val,"VSID","|"))&&(vid.length!=0)){if((DateToMS(getTStamp())-DateToMS(getCV(c_val,"LVIS","|")))/(3600000)>=ses_hrs){var nvis=parseInt(getCV(c_val,"NVIS","|"));
var fvis=(DateToMS(getTStamp())-DateToMS(getCV(c_val,"LVIS","|")))/(1000*60*60*ses_hrs);fvis=Math.round(fvis);c_val=setCKV(c_val,"LVIS",getTStamp(),"|");
c_val=setCKV(c_val,"NVIS",++nvis,"|");c_val=setCKV(c_val,"FVIS",fvis,"|");var floorVSIDDate=Math.max(DateToMS(getCV(c_val,"VSID","|")),Date.parse("Nov 17, 2002"));
actf=(nvis/((DateToMS(getTStamp())-floorVSIDDate)/(1000*60*60*ses_hrs)))*100;if(actf>100){actf=100;}if(actf<0){actf=0;}c_val=setCKV(c_val,"ACTF",Math.round(actf),"|");
}if(getCV(c_val,"MEMB","|")=="0"){c_val=setCKV(c_val,"MEMB",_s[0],"|");}SetCookie(cactv,c_val,getExpDate(365),"/",c_domain,false);}else{if(getCV(c_val,"MEMB","|")==null){c_val=setCKV(c_val,"MEMB",_s[0],"|");
}c_val=setCKV(c_val,"VSID",getVSID(),"|");c_val=setCKV(c_val,"LVIS",getTStamp(),"|");c_val=setCKV(c_val,"NVIS","1","|");c_val=setCKV(c_val,"ACTF",0,"|");
c_val=setCKV(c_val,"FVIS",0,"|");SetCookie(cactv,c_val,getExpDate(365),"/",c_domain,false);}}function DateToMS(tstamp){var a=tstamp.split("-");if(a[1]>0){a[1]--;
}for(var i=a.length;i<7;i++){a[i]=0;}return Date.UTC(a[0],a[1],a[2],a[3],a[4],a[5],a[6]);}function set_source_url(){var c_val="";var isrc="";var esrc="";
var ploc=checkInternal(document.URL);if(c_val=GetCookie(cname)){if((isrc=getCV(c_val,"PLOC","|"))&&document.referrer){isrc=checkInternal(isrc);}else{isrc="NOSOURCE";
}c_val=setCKV(c_val,"ISRC",escape(isrc),"|");c_val=setCKV(c_val,"PLOC",escape(ploc),"|");var step=parseInt(getCV(c_val,"STEP","|"));if(isNaN(step)){step=0;
}c_val=setCKV(c_val,"STEP",step+1,"|");SetCookie(cname,c_val,null,"/",c_domain,false);}else{if(esrc=getValueByKey("ESRC")){}else{if(document.referrer!=null&&document.referrer!=""&&document.referrer.length!=0){esrc=getDomain(document.referrer);
}else{esrc="NOSOURCE";}}c_val="ESRC"+escape(esrc)+"|ISRCNOSOURCE|STEP1|PLOC"+escape(ploc);SetCookie(cname,c_val,null,"/",c_domain,false);}}function set_location(url){var c_val="";
if(c_val=GetCookie(cname)){c_val=setCKV(c_val,"PLOC",escape(url),"|");SetCookie(cname,c_val,null,"/",c_domain,false);}_URL=url;}function unifyURL(url){if(url.split("://").length<2){return url;
}var t=getDomain(url);t=t.toLowerCase();if(t.split(".")[0]=="military"){t="www."+t;}return t+"/"+remove_url_domain(url);}function removeHTTP(url){if(url.split("://").length<2){return escape(url);
}else{return escape(url.split("://")[1]);}}function setDisplay(){var url="1";var ck=true;var red="http://tracking.military.com/cgi-bin/redlog2.cgi";var sr_cvalue=GetCookie(cname,1);
var ac_cvalue=GetCookie(cactv);if(sr_cvalue==null||sr_cvalue.length==0){ck=false;}var esrc=(ck)?removeHTTP(unifyURL(getDomain(unescape(getCV(sr_cvalue,"ESRC","|"))))):"UNKNOWN";
var isrc=(ck)?removeHTTP(unifyURL(unescape(getCV(sr_cvalue,"ISRC","|")))):"UNKNOWN";var ploc=(ck)?removeHTTP(unifyURL(unescape(getCV(sr_cvalue,"PLOC","|")))):removeHTTP(unifyURL(checkInternal(_URL)));
var stat=_s[6];var serv=_s[5];var vage=(_age)?_age:"0";var step=(ck)?getCV(sr_cvalue,"STEP","|"):"0";var vsid=(ck)?getCV(ac_cvalue,"VSID","|"):"0";var memb=(ck)?getCV(ac_cvalue,"MEMB","|"):_s[0];
var nvis=(ck)?getCV(ac_cvalue,"NVIS","|"):"0";var actf=(ck)?getCV(ac_cvalue,"ACTF","|"):"0";var fvis=(ck)?getCV(ac_cvalue,"FVIS","|"):"0";var d=new Date();
var r=d.getSeconds()*Math.random();var imgsrc=red+"?url="+url+"&ploc="+ploc+"&step="+step+"&esrc="+esrc+"&isrc="+isrc+"&vsid="+vsid+"&memb="+memb+"&nvis="+nvis+"&actf="+actf+"&fvis="+fvis+"&stat="+stat+"&serv="+serv+"&vage="+vage+"&rand="+r;
Display=" <img src='"+imgsrc+"' width='1' height='1'>";}function getCVA(s,d){var ta=new Array();if(s==null){return ta;}ta=s.split(d);var kva=new Array();
for(var x=0;x<ta.length;x++){kva[ta[x].substring(0,4)]=ta[x].substring(4);}return kva;}function setCKV(s,k,v,d){var ta=new Array();ta=getCVA(s,d);ta[k]=v;
var nta=new Array();for(key in ta){if(key!="push"){nta.push(key+""+ta[key]);}}return nta.join(d);}function getCV(s,k,d){var ta=new Array();ta=getCVA(s,d);
return ta[k];}function loadPopUnder(){if(document.cookie.length<=0){return;}var esrc="";if(c_val=GetCookie("SRCT")){esrc=getCV(c_val,"ESRC","|");}if(document.URL.match(/np=1/i)!=null||esrc.match(/\.kw$/i)!=null){SetCookie("pop_news","1",null,"/",c_domain,false);
}if(typeof no_popunder!="undefined"){return;}if(typeof popup_ckn!="undefined"&&!GetCookie(popup_ckn)){return;}var actname=GetCookie("ACTV");var actkeyfound=-1;
if(actname!=null){actkeyfound=actname.indexOf("NWLDY");}if((actname==null||actkeyfound==-1)&&document.URL.match(/np=1/i)==null&&esrc.match(/\.kw$/i)==null){open_window("http://www.military.com/Data/Popup/New_Education_Popunder.htm","pop_news",830,420,"TL",1,14,1);
var exp=new Date();exp.setTime(exp.getTime()+(14*24*60*60*1000));SetCookie("pop_news",1,exp,"/",c_domain,false);}else{SetCookie("pop_news","1",null,"/",c_domain,false);
}}function closePopup(ckname){if(typeof no_closepopup!="undefined"){return;}var ck=GetCookie(ckname);if(ck==null||ck==""){return;}var popup=window.open("",ck);
if(popup&&!popup.closed){popup.close();}SetCookie(ckname,"",null,"/",".military.com");}function milcore_RegisterPopUnderEvent(){if(window.addEventListener){window.addEventListener("load",loadPopUnder,false);
}else{window.attachEvent("onload",loadPopUnder);}}function startT(){setVID();set_source_url();setDisplay();closePopup("MiniPop");}startT();loaded="true";
function logAsset(siteName,objType,objId,objName,objURL){var jsParam="";if(self.StatPixelParamFromPage){jsParam=StatPixelParamFromPage;}var color="n/a";
var size="n/a";var puri="";var java=navigator.javaEnabled();var nav=navigator.appName;var agent=navigator.userAgent;var objValue="";var write=(navigator.appName=="Netscape"&&(navigator.appVersion.charAt(0)=="2"||navigator.appVersion.charAt(0)=="3"))?false:true;
if(write==true){size=screen.width+"x"+screen.height;color=(nav!="Netscape")?screen.colorDepth:screen.pixelDepth;objValue=encodeURIComponent(objName);puri="?siteName="+siteName+"&objType="+objType+"&objID="+objId+"&objName="+objValue+"&sessionID="+getSessionID()+"&Referer="+escape(document.referrer)+"&nav="+nav+"&agent="+agent+"&size="+size+"&color="+color+"&java="+java+"&js=true"+jsParam;
var url=new String(document.location);var index=url.indexOf("?");if(index>-1){var query=url.substring(index+1);var params=query.split("&");var args=new Array();
for(i in params){var nvpair=params[i].split("=");if(nvpair.length==2){if(nvpair[0]=="col"){puri+="&recID="+nvpair[1]+"&segID=0";break;}}}}if(objURL!=undefined){puri+="&URLENC="+objURL;
}document.write('<img style="display:none;" height="1" width="1" border="0" src="/sensor/statistic'+puri+'" alt="pixel" />');}}function logRecommendation(siteName,objId,objName,lstSegments,lstAssetID,lstAssetType,lstAssetName){var puri="";
var objValue="";if(lstAssetID==null){return;}var write=(navigator.appName=="Netscape"&&(navigator.appVersion.charAt(0)=="2"||navigator.appVersion.charAt(0)=="3"))?false:true;
if(write==true){size=screen.width+"x"+screen.height;objValue=encodeURIComponent(objName);puri="?siteName="+siteName+"&objID="+objId+"&objName="+objValue+"&segID="+lstSegments+"&sessionID="+getSessionID()+"&size="+size;
document.write('<img style="display:none;" height="1" width="1" border="0" src="/sensor/statistic'+puri+'&objType=RecAsked" alt="pixel" />');puri+="&objType=RecListed&objListID="+lstAssetID+"&objListType="+lstAssetType+"&objListName="+lstAssetName;
document.write('<img style="display:none;" height="1" width="1" border="0" src="/sensor/statistic'+puri+'" alt="pixel" />');}}function AjaxEvent(url,callback,contenttype){this.url=url;
this.callback=callback;this.contenttype=(contenttype==undefined)?"application/x-www-form-urlencoded":contenttype;}function AjaxEngine(){this.method="POST";
this.async=true;this.events=new Array();this.request=window.XMLHttpRequest?new XMLHttpRequest():new ActiveXObject("MSXML2.XMLHTTP.3.0");}AjaxEngine.prototype.register=function(name,url,callback){this.events[name]=new AjaxEvent(url,callback);
};AjaxEngine.prototype.send=function(name,params){var request=this.request;var event=this.events[name];if(event==null){return;}request.open(this.method,event.url,this.async);
if(params==undefined){request.send(null);}else{request.setRequestHeader("Content-Type",event.contenttype);request.send(params);}request.onreadystatechange=function(){if(request.readyState==4&&request.status==200){if(request.responseText){event.callback(request);
}}};};var Ajax=new AjaxEngine();String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"");};function getSessionID(){if(document.cookie==null||document.cookie==""){return"";
}var tempArr=new Array();tempArr=document.cookie.split(";");var sessionID="";var cookiePrefix="MASESSION";for(var i=0;i<tempArr.length;i++){var nvPairArr=new Array();
var tempStr=new String(tempArr[i]);nvPairArr=tempStr.trim().split("=");if(nvPairArr[0].indexOf(cookiePrefix)>-1){sessionID=nvPairArr[1];break;}}return sessionID;
}document.getElementsByClassName=function(cl,fromObjId){var retnode=[];var myclass=new RegExp("\\b"+cl+"\\b");var elem;if(fromObjId==null){elem=this.getElementsByTagName("*");
}else{var obj=document.getElementById(fromObjId);if(obj==null){return null;}elem=obj.getElementsByTagName("*");}for(var i=0;i<elem.length;i++){var classes=elem[i].className;
if(myclass.test(classes)){retnode.push(elem[i]);}}return retnode;};var newwindow="";function popTheMusterPoll(poll){var url="http://www.military.com/hp/poll";
if(poll!=""){url=url+"?poll="+poll;}var popup_name="themusterpoll";var window_specs="toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=716,height=515";
if(!newwindow.closed&&newwindow.location){newwindow.location.href=url;}else{newwindow=window.open(url,popup_name,window_specs);if(!newwindow.opener){newwindow.opener=self;
}}if(window.focus){newwindow.focus();}return false;}function showTab(tabNum,fromObjId){var selectedTab="tab"+tabNum;var tabs=document.getElementsByClassName("tab",fromObjId);
for(var i=0;i<tabs.length;i++){var tabObj=tabs[i];if(tabObj==null){continue;}tabObj.className=tabObj.className.replace(new RegExp(" selected\\b"),"");if(tabObj.id==selectedTab){tabObj.className+=" selected";
}}var selectedTabContent_name="tab"+tabNum+"_content";var tabcontents=document.getElementsByClassName("tabContent",fromObjId);for(var i=0;i<tabcontents.length;
i++){var tabObj=tabcontents[i];if(tabObj==null){continue;}if(tabObj.id==selectedTabContent_name){tabObj.style.display="block";}else{tabObj.style.display="none";
}}}function rotateList(){$(".randomList ul").each(function(){$("li",this).each(function(index){$(this).removeClass("active");});var length=$("li",this).length;
var rdm=Math.floor(Math.random()*length)+1;$("li:nth-child("+rdm+")",this).addClass("active");});window.setTimeout("rotateList()",15000);}window.setTimeout("rotateList()",1000);
